// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _apply_kernel_single_s_HH_
#define _apply_kernel_single_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct apply_kernel_single_s : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<8> > input_0_0_read;
    sc_in< sc_lv<8> > input_0_1_read;
    sc_in< sc_lv<8> > input_0_2_read;
    sc_in< sc_lv<8> > input_1_0_read;
    sc_in< sc_lv<8> > input_1_1_read;
    sc_in< sc_lv<8> > input_1_2_read;
    sc_in< sc_lv<8> > input_2_0_read;
    sc_in< sc_lv<8> > input_2_1_read;
    sc_in< sc_lv<8> > input_2_2_read;


    // Module declarations
    apply_kernel_single_s(sc_module_name name);
    SC_HAS_PROCESS(apply_kernel_single_s);

    ~apply_kernel_single_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_start;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<5> > ap_return;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_start();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
