-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HLS_accel is
generic (
    C_S_AXI_CONTROL_BUS_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    INPUT_STREAM_TVALID : IN STD_LOGIC;
    INPUT_STREAM_TREADY : OUT STD_LOGIC;
    INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (4 downto 0);
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC;
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (4 downto 0);
    s_axi_CONTROL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CONTROL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CONTROL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of HLS_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "HLS_accel,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.232000,HLS_SYN_LAT=4782356,HLS_SYN_TPT=none,HLS_SYN_MEM=68,HLS_SYN_DSP=14,HLS_SYN_FF=2585,HLS_SYN_LUT=5354,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_ap_start : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_ap_done : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_ap_idle : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_ap_ready : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY : STD_LOGIC;
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_wrapped_HCD_filter_h_fu_52_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_INPUT_STREAM_data_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal INPUT_STREAM_TVALID_int : STD_LOGIC;
    signal INPUT_STREAM_TREADY_int : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_keep_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_INPUT_STREAM_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_strb_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_INPUT_STREAM_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_user_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TUSER_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_INPUT_STREAM_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_last_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_INPUT_STREAM_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_id_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TID_int : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_INPUT_STREAM_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_dest_V_U_apdone_blk : STD_LOGIC;
    signal INPUT_STREAM_TDEST_int : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_INPUT_STREAM_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_INPUT_STREAM_dest_V_U_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_TREADY_int : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_dest_V_U_vld_out : STD_LOGIC;

    component wrapped_HCD_filter_h IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        INPUT_STREAM_TVALID : IN STD_LOGIC;
        INPUT_STREAM_TREADY : OUT STD_LOGIC;
        OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
        OUTPUT_STREAM_TREADY : IN STD_LOGIC;
        OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component HLS_accel_CONTROL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    HLS_accel_CONTROL_BUS_s_axi_U : component HLS_accel_CONTROL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CONTROL_BUS_AWVALID,
        AWREADY => s_axi_CONTROL_BUS_AWREADY,
        AWADDR => s_axi_CONTROL_BUS_AWADDR,
        WVALID => s_axi_CONTROL_BUS_WVALID,
        WREADY => s_axi_CONTROL_BUS_WREADY,
        WDATA => s_axi_CONTROL_BUS_WDATA,
        WSTRB => s_axi_CONTROL_BUS_WSTRB,
        ARVALID => s_axi_CONTROL_BUS_ARVALID,
        ARREADY => s_axi_CONTROL_BUS_ARREADY,
        ARADDR => s_axi_CONTROL_BUS_ARADDR,
        RVALID => s_axi_CONTROL_BUS_RVALID,
        RREADY => s_axi_CONTROL_BUS_RREADY,
        RDATA => s_axi_CONTROL_BUS_RDATA,
        RRESP => s_axi_CONTROL_BUS_RRESP,
        BVALID => s_axi_CONTROL_BUS_BVALID,
        BREADY => s_axi_CONTROL_BUS_BREADY,
        BRESP => s_axi_CONTROL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    grp_wrapped_HCD_filter_h_fu_52 : component wrapped_HCD_filter_h
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_wrapped_HCD_filter_h_fu_52_ap_start,
        ap_done => grp_wrapped_HCD_filter_h_fu_52_ap_done,
        ap_idle => grp_wrapped_HCD_filter_h_fu_52_ap_idle,
        ap_ready => grp_wrapped_HCD_filter_h_fu_52_ap_ready,
        INPUT_STREAM_TDATA => INPUT_STREAM_TDATA_int,
        INPUT_STREAM_TVALID => INPUT_STREAM_TVALID_int,
        INPUT_STREAM_TREADY => grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY,
        OUTPUT_STREAM_TDATA => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST);

    regslice_both_INPUT_STREAM_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TDATA,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_data_V_U_ack_in,
        data_out => INPUT_STREAM_TDATA_int,
        vld_out => INPUT_STREAM_TVALID_int,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_data_V_U_apdone_blk);

    regslice_both_INPUT_STREAM_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TKEEP,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_keep_V_U_ack_in,
        data_out => INPUT_STREAM_TKEEP_int,
        vld_out => regslice_both_INPUT_STREAM_keep_V_U_vld_out,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_keep_V_U_apdone_blk);

    regslice_both_INPUT_STREAM_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TSTRB,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_strb_V_U_ack_in,
        data_out => INPUT_STREAM_TSTRB_int,
        vld_out => regslice_both_INPUT_STREAM_strb_V_U_vld_out,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_strb_V_U_apdone_blk);

    regslice_both_INPUT_STREAM_user_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TUSER,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_user_V_U_ack_in,
        data_out => INPUT_STREAM_TUSER_int,
        vld_out => regslice_both_INPUT_STREAM_user_V_U_vld_out,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_user_V_U_apdone_blk);

    regslice_both_INPUT_STREAM_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TLAST,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_last_V_U_ack_in,
        data_out => INPUT_STREAM_TLAST_int,
        vld_out => regslice_both_INPUT_STREAM_last_V_U_vld_out,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_last_V_U_apdone_blk);

    regslice_both_INPUT_STREAM_id_V_U : component regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TID,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_id_V_U_ack_in,
        data_out => INPUT_STREAM_TID_int,
        vld_out => regslice_both_INPUT_STREAM_id_V_U_vld_out,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_id_V_U_apdone_blk);

    regslice_both_INPUT_STREAM_dest_V_U : component regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => INPUT_STREAM_TDEST,
        vld_in => INPUT_STREAM_TVALID,
        ack_in => regslice_both_INPUT_STREAM_dest_V_U_ack_in,
        data_out => INPUT_STREAM_TDEST_int,
        vld_out => regslice_both_INPUT_STREAM_dest_V_U_vld_out,
        ack_out => INPUT_STREAM_TREADY_int,
        apdone_blk => regslice_both_INPUT_STREAM_dest_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => OUTPUT_STREAM_TREADY_int,
        data_out => OUTPUT_STREAM_TDATA,
        vld_out => regslice_both_OUTPUT_STREAM_data_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_keep_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TKEEP,
        vld_out => regslice_both_OUTPUT_STREAM_keep_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_keep_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_strb_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TSTRB,
        vld_out => regslice_both_OUTPUT_STREAM_strb_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_strb_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_user_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_user_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TUSER,
        vld_out => regslice_both_OUTPUT_STREAM_user_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_user_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_last_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TLAST,
        vld_out => regslice_both_OUTPUT_STREAM_last_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_last_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_id_V_U : component regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_id_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TID,
        vld_out => regslice_both_OUTPUT_STREAM_id_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_id_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_dest_V_U : component regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST,
        vld_in => grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_dest_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TDEST,
        vld_out => regslice_both_OUTPUT_STREAM_dest_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_wrapped_HCD_filter_h_fu_52_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_wrapped_HCD_filter_h_fu_52_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_wrapped_HCD_filter_h_fu_52_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_wrapped_HCD_filter_h_fu_52_ap_ready = ap_const_logic_1)) then 
                    grp_wrapped_HCD_filter_h_fu_52_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_wrapped_HCD_filter_h_fu_52_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_wrapped_HCD_filter_h_fu_52_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    INPUT_STREAM_TREADY_assign_proc : process(INPUT_STREAM_TVALID, regslice_both_INPUT_STREAM_data_V_U_ack_in)
    begin
        if (((ap_const_logic_1 = INPUT_STREAM_TVALID) and (regslice_both_INPUT_STREAM_data_V_U_ack_in = ap_const_logic_1))) then 
            INPUT_STREAM_TREADY <= ap_const_logic_1;
        else 
            INPUT_STREAM_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    INPUT_STREAM_TREADY_int_assign_proc : process(grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            INPUT_STREAM_TREADY_int <= grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY;
        else 
            INPUT_STREAM_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_TVALID <= regslice_both_OUTPUT_STREAM_data_V_U_vld_out;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_CS_fsm_state4, regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY <= (ap_CS_fsm_state3 and OUTPUT_STREAM_TREADY_int);
    grp_wrapped_HCD_filter_h_fu_52_ap_start <= grp_wrapped_HCD_filter_h_fu_52_ap_start_reg;
end behav;
