-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity apply_kernel_single_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_0_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_0_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_1_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_1_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_1_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_2_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_2_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
    input_2_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of apply_kernel_single_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv18_1C8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000111001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln40_4_fu_94_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_4_reg_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_fu_100_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_reg_159 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln40_1_fu_106_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_1_reg_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_3_fu_112_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_3_reg_169 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_5_fu_118_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_5_reg_174 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_2_fu_123_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_2_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln40_6_fu_127_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln40_6_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_fu_131_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_reg_189 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal mul_ln43_fu_138_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln43_fu_138_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln43_fu_138_p00 : STD_LOGIC_VECTOR (17 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln40_1_reg_164 <= add_ln40_1_fu_106_p2;
                add_ln40_3_reg_169 <= add_ln40_3_fu_112_p2;
                add_ln40_5_reg_174 <= add_ln40_5_fu_118_p2;
                add_ln40_reg_159 <= add_ln40_fu_100_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln40_2_reg_179 <= add_ln40_2_fu_123_p2;
                add_ln40_6_reg_184 <= add_ln40_6_fu_127_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                add_ln40_4_reg_154 <= add_ln40_4_fu_94_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                ap_return <= mul_ln43_fu_138_p2(16 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sum_reg_189 <= sum_fu_131_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln40_1_fu_106_p2 <= std_logic_vector(unsigned(input_2_0_read) + unsigned(input_0_1_read));
    add_ln40_2_fu_123_p2 <= std_logic_vector(unsigned(add_ln40_1_reg_164) + unsigned(add_ln40_reg_159));
    add_ln40_3_fu_112_p2 <= std_logic_vector(unsigned(input_1_1_read) + unsigned(input_2_1_read));
    add_ln40_4_fu_94_p2 <= std_logic_vector(unsigned(input_1_2_read) + unsigned(input_2_2_read));
    add_ln40_5_fu_118_p2 <= std_logic_vector(unsigned(input_0_2_read) + unsigned(add_ln40_4_reg_154));
    add_ln40_6_fu_127_p2 <= std_logic_vector(unsigned(add_ln40_5_reg_174) + unsigned(add_ln40_3_reg_169));
    add_ln40_fu_100_p2 <= std_logic_vector(unsigned(input_1_0_read) + unsigned(input_0_0_read));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln43_fu_138_p0 <= mul_ln43_fu_138_p00(8 - 1 downto 0);
    mul_ln43_fu_138_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_reg_189),18));
    mul_ln43_fu_138_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln43_fu_138_p0) * unsigned(ap_const_lv18_1C8), 18));
    sum_fu_131_p2 <= std_logic_vector(unsigned(add_ln40_6_reg_184) + unsigned(add_ln40_2_reg_179));
end behav;
