// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "HCD_filter_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic HCD_filter_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic HCD_filter_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state1 = "1";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state2 = "10";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state3 = "100";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state4 = "1000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state5 = "10000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state6 = "100000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state7 = "1000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state8 = "10000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state9 = "100000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state10 = "1000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state11 = "10000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state12 = "100000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<40> HCD_filter_hw::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_13 = "10011";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_1A = "11010";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_19 = "11001";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_1F = "11111";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_24 = "100100";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_2 = "10";
const sc_lv<1> HCD_filter_hw::ap_const_lv1_1 = "1";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_3 = "11";
const sc_lv<1> HCD_filter_hw::ap_const_lv1_0 = "0";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_4 = "100";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_5 = "101";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_7 = "111";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_8 = "1000";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_9 = "1001";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_A = "1010";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_B = "1011";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_C = "1100";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_D = "1101";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_E = "1110";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_14 = "10100";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_15 = "10101";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_25 = "100101";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_26 = "100110";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_27 = "100111";
const sc_lv<8> HCD_filter_hw::ap_const_lv8_1 = "1";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_1 = "1";
const sc_lv<3> HCD_filter_hw::ap_const_lv3_7 = "111";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_6 = "110";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_1 = "1";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_2 = "10";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_3 = "11";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_4 = "100";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_5 = "101";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_6 = "110";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_7 = "111";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_8 = "1000";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_1B = "11011";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_20 = "100000";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_3FA47AE147AE147B = "11111110100100011110101110000101000111101011100001010001111011";
const sc_lv<64> HCD_filter_hw::ap_const_lv64_407F400000000000 = "100000001111111010000000000000000000000000000000000000000000000";
const sc_lv<8> HCD_filter_hw::ap_const_lv8_FF = "11111111";
const sc_lv<3> HCD_filter_hw::ap_const_lv3_2 = "10";
const sc_lv<3> HCD_filter_hw::ap_const_lv3_1 = "1";
const sc_lv<2> HCD_filter_hw::ap_const_lv2_0 = "00";
const sc_lv<18> HCD_filter_hw::ap_const_lv18_1C8 = "111001000";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_11 = "10001";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_34 = "110100";
const sc_lv<32> HCD_filter_hw::ap_const_lv32_3E = "111110";
const sc_lv<11> HCD_filter_hw::ap_const_lv11_7FF = "11111111111";
const sc_lv<52> HCD_filter_hw::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<5> HCD_filter_hw::ap_const_lv5_2 = "10";
const bool HCD_filter_hw::ap_const_boolean_1 = true;

HCD_filter_hw::HCD_filter_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Ix2_window_U = new HCD_filter_hw_Ix2bkb("Ix2_window_U");
    Ix2_window_U->clk(ap_clk);
    Ix2_window_U->reset(ap_rst);
    Ix2_window_U->address0(Ix2_window_address0);
    Ix2_window_U->ce0(Ix2_window_ce0);
    Ix2_window_U->we0(Ix2_window_we0);
    Ix2_window_U->d0(Ix2_window_d0);
    Ix2_window_U->q0(Ix2_window_q0);
    Ix2_window_U->address1(Ix2_window_address1);
    Ix2_window_U->ce1(Ix2_window_ce1);
    Ix2_window_U->q1(Ix2_window_q1);
    Iy2_window_U = new HCD_filter_hw_Ix2bkb("Iy2_window_U");
    Iy2_window_U->clk(ap_clk);
    Iy2_window_U->reset(ap_rst);
    Iy2_window_U->address0(Iy2_window_address0);
    Iy2_window_U->ce0(Iy2_window_ce0);
    Iy2_window_U->we0(Iy2_window_we0);
    Iy2_window_U->d0(Iy2_window_d0);
    Iy2_window_U->q0(Iy2_window_q0);
    Iy2_window_U->address1(Iy2_window_address1);
    Iy2_window_U->ce1(Iy2_window_ce1);
    Iy2_window_U->q1(Iy2_window_q1);
    Ixy_window_U = new HCD_filter_hw_Ix2bkb("Ixy_window_U");
    Ixy_window_U->clk(ap_clk);
    Ixy_window_U->reset(ap_rst);
    Ixy_window_U->address0(Ixy_window_address0);
    Ixy_window_U->ce0(Ixy_window_ce0);
    Ixy_window_U->we0(Ixy_window_we0);
    Ixy_window_U->d0(Ixy_window_d0);
    Ixy_window_U->q0(Ixy_window_q0);
    Ixy_window_U->address1(Ixy_window_address1);
    Ixy_window_U->ce1(Ixy_window_ce1);
    Ixy_window_U->q1(Ixy_window_q1);
    HLS_accel_dsub_64eOg_U2 = new HLS_accel_dsub_64eOg<1,5,64,64,64>("HLS_accel_dsub_64eOg_U2");
    HLS_accel_dsub_64eOg_U2->clk(ap_clk);
    HLS_accel_dsub_64eOg_U2->reset(ap_rst);
    HLS_accel_dsub_64eOg_U2->din0(grp_fu_437_p0);
    HLS_accel_dsub_64eOg_U2->din1(grp_fu_437_p1);
    HLS_accel_dsub_64eOg_U2->ce(ap_var_for_const0);
    HLS_accel_dsub_64eOg_U2->dout(grp_fu_437_p2);
    HLS_accel_dmul_64fYi_U3 = new HLS_accel_dmul_64fYi<1,6,64,64,64>("HLS_accel_dmul_64fYi_U3");
    HLS_accel_dmul_64fYi_U3->clk(ap_clk);
    HLS_accel_dmul_64fYi_U3->reset(ap_rst);
    HLS_accel_dmul_64fYi_U3->din0(grp_fu_441_p0);
    HLS_accel_dmul_64fYi_U3->din1(grp_fu_441_p1);
    HLS_accel_dmul_64fYi_U3->ce(ap_var_for_const0);
    HLS_accel_dmul_64fYi_U3->dout(grp_fu_441_p2);
    HLS_accel_dcmp_64g8j_U4 = new HLS_accel_dcmp_64g8j<1,2,64,64,1>("HLS_accel_dcmp_64g8j_U4");
    HLS_accel_dcmp_64g8j_U4->clk(ap_clk);
    HLS_accel_dcmp_64g8j_U4->reset(ap_rst);
    HLS_accel_dcmp_64g8j_U4->din0(reg_488);
    HLS_accel_dcmp_64g8j_U4->din1(ap_var_for_const1);
    HLS_accel_dcmp_64g8j_U4->ce(ap_var_for_const0);
    HLS_accel_dcmp_64g8j_U4->opcode(ap_var_for_const2);
    HLS_accel_dcmp_64g8j_U4->dout(grp_fu_446_p2);
    HLS_accel_sitodp_hbi_U5 = new HLS_accel_sitodp_hbi<1,6,32,64>("HLS_accel_sitodp_hbi_U5");
    HLS_accel_sitodp_hbi_U5->clk(ap_clk);
    HLS_accel_sitodp_hbi_U5->reset(ap_rst);
    HLS_accel_sitodp_hbi_U5->din0(grp_fu_451_p0);
    HLS_accel_sitodp_hbi_U5->ce(ap_var_for_const0);
    HLS_accel_sitodp_hbi_U5->dout(grp_fu_451_p1);
    HLS_accel_sitodp_hbi_U6 = new HLS_accel_sitodp_hbi<1,6,32,64>("HLS_accel_sitodp_hbi_U6");
    HLS_accel_sitodp_hbi_U6->clk(ap_clk);
    HLS_accel_sitodp_hbi_U6->reset(ap_rst);
    HLS_accel_sitodp_hbi_U6->din0(grp_fu_454_p0);
    HLS_accel_sitodp_hbi_U6->ce(ap_var_for_const0);
    HLS_accel_sitodp_hbi_U6->dout(grp_fu_454_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_I_x_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln66_1_fu_575_p1 );

    SC_METHOD(thread_I_x_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_I_y_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln66_1_fu_575_p1 );

    SC_METHOD(thread_I_y_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_Ix2_window_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln66_fu_601_p1 );

    SC_METHOD(thread_Ix2_window_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_Ix2_window_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Ix2_window_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_Ix2_window_d0);
    sensitive << ( I_x_load_reg_1060 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Ix2_window_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Ixy_window_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln66_fu_601_p1 );

    SC_METHOD(thread_Ixy_window_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_Ixy_window_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Ixy_window_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_Ixy_window_d0);
    sensitive << ( I_x_load_reg_1060 );
    sensitive << ( I_y_load_reg_1067 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Ixy_window_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Iy2_window_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln66_fu_601_p1 );

    SC_METHOD(thread_Iy2_window_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_Iy2_window_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Iy2_window_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_Iy2_window_d0);
    sensitive << ( I_y_load_reg_1067 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Iy2_window_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_add_ln40_10_fu_669_p2);
    sensitive << ( add_ln40_8_reg_1079 );
    sensitive << ( add_ln40_9_reg_1094 );

    SC_METHOD(thread_add_ln40_11_fu_673_p2);
    sensitive << ( Iy2_window_load_3_reg_1109 );
    sensitive << ( Iy2_window_load_4_reg_1129 );

    SC_METHOD(thread_add_ln40_12_fu_628_p2);
    sensitive << ( Iy2_window_q1 );
    sensitive << ( Iy2_window_q0 );

    SC_METHOD(thread_add_ln40_13_fu_634_p2);
    sensitive << ( Iy2_window_load_5_reg_1134 );
    sensitive << ( add_ln40_12_fu_628_p2 );

    SC_METHOD(thread_add_ln40_14_fu_677_p2);
    sensitive << ( add_ln40_13_reg_1154 );
    sensitive << ( add_ln40_11_fu_673_p2 );

    SC_METHOD(thread_add_ln40_18_fu_688_p2);
    sensitive << ( add_ln40_16_reg_1084 );
    sensitive << ( add_ln40_17_reg_1099 );

    SC_METHOD(thread_add_ln40_19_fu_692_p2);
    sensitive << ( Ixy_window_load_3_reg_1114 );
    sensitive << ( Ixy_window_load_4_reg_1139 );

    SC_METHOD(thread_add_ln40_20_fu_639_p2);
    sensitive << ( Ixy_window_q1 );
    sensitive << ( Ixy_window_q0 );

    SC_METHOD(thread_add_ln40_21_fu_645_p2);
    sensitive << ( Ixy_window_load_5_reg_1144 );
    sensitive << ( add_ln40_20_fu_639_p2 );

    SC_METHOD(thread_add_ln40_22_fu_696_p2);
    sensitive << ( add_ln40_21_reg_1159 );
    sensitive << ( add_ln40_19_fu_692_p2 );

    SC_METHOD(thread_add_ln40_2_fu_650_p2);
    sensitive << ( add_ln40_reg_1074 );
    sensitive << ( add_ln40_1_reg_1089 );

    SC_METHOD(thread_add_ln40_3_fu_654_p2);
    sensitive << ( Ix2_window_load_3_reg_1104 );
    sensitive << ( Ix2_window_load_4_reg_1119 );

    SC_METHOD(thread_add_ln40_4_fu_617_p2);
    sensitive << ( Ix2_window_q1 );
    sensitive << ( Ix2_window_q0 );

    SC_METHOD(thread_add_ln40_5_fu_623_p2);
    sensitive << ( Ix2_window_load_5_reg_1124 );
    sensitive << ( add_ln40_4_fu_617_p2 );

    SC_METHOD(thread_add_ln40_6_fu_658_p2);
    sensitive << ( add_ln40_5_reg_1149 );
    sensitive << ( add_ln40_3_fu_654_p2 );

    SC_METHOD(thread_add_ln66_1_fu_591_p2);
    sensitive << ( sub_ln66_reg_1032 );
    sensitive << ( zext_ln66_2_fu_587_p1 );

    SC_METHOD(thread_add_ln79_fu_764_p2);
    sensitive << ( tmp_11_reg_1179 );
    sensitive << ( tmp_12_reg_1185 );

    SC_METHOD(thread_and_ln83_fu_848_p2);
    sensitive << ( or_ln83_fu_844_p2 );
    sensitive << ( grp_fu_446_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln54_fu_494_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln54_fu_494_p2 );

    SC_METHOD(thread_bitcast_ln83_fu_814_p1);
    sensitive << ( reg_488 );

    SC_METHOD(thread_grp_fu_437_p0);
    sensitive << ( reg_475 );
    sensitive << ( reg_488 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_grp_fu_437_p1);
    sensitive << ( reg_482 );
    sensitive << ( tmp_4_reg_1221 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_grp_fu_441_p0);
    sensitive << ( reg_475 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( reg_482 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_grp_fu_441_p1);
    sensitive << ( reg_475 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_grp_fu_451_p0);
    sensitive << ( zext_ln79_fu_768_p1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln78_2_fu_806_p1 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_fu_454_p0);
    sensitive << ( mul_ln78_1_reg_1206 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_fu_457_p2);
    sensitive << ( Ix2_window_q1 );
    sensitive << ( Ix2_window_q0 );

    SC_METHOD(thread_grp_fu_463_p2);
    sensitive << ( Iy2_window_q1 );
    sensitive << ( Iy2_window_q0 );

    SC_METHOD(thread_grp_fu_469_p2);
    sensitive << ( Ixy_window_q1 );
    sensitive << ( Ixy_window_q0 );

    SC_METHOD(thread_icmp_ln54_fu_494_p2);
    sensitive << ( y_0_reg_391 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_icmp_ln55_fu_500_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( x_0_reg_403 );

    SC_METHOD(thread_icmp_ln62_fu_516_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ky_0_reg_415 );

    SC_METHOD(thread_icmp_ln63_fu_556_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( kx_0_reg_426 );

    SC_METHOD(thread_icmp_ln83_1_fu_838_p2);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( trunc_ln83_fu_828_p1 );

    SC_METHOD(thread_icmp_ln83_fu_832_p2);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( tmp_2_fu_818_p4 );

    SC_METHOD(thread_kx_fu_581_p2);
    sensitive << ( kx_0_reg_426 );

    SC_METHOD(thread_ky_fu_528_p2);
    sensitive << ( ky_0_reg_415 );

    SC_METHOD(thread_mul_ln43_1_fu_729_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( mul_ln43_1_fu_729_p10 );

    SC_METHOD(thread_mul_ln43_1_fu_729_p10);
    sensitive << ( sum_3_reg_1169 );

    SC_METHOD(thread_mul_ln43_1_fu_729_p2);
    sensitive << ( mul_ln43_1_fu_729_p1 );

    SC_METHOD(thread_mul_ln43_2_fu_748_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( mul_ln43_2_fu_748_p10 );

    SC_METHOD(thread_mul_ln43_2_fu_748_p10);
    sensitive << ( sum_5_reg_1174 );

    SC_METHOD(thread_mul_ln43_2_fu_748_p2);
    sensitive << ( mul_ln43_2_fu_748_p1 );

    SC_METHOD(thread_mul_ln43_fu_710_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( mul_ln43_fu_710_p10 );

    SC_METHOD(thread_mul_ln43_fu_710_p10);
    sensitive << ( sum_1_reg_1164 );

    SC_METHOD(thread_mul_ln43_fu_710_p2);
    sensitive << ( mul_ln43_fu_710_p1 );

    SC_METHOD(thread_mul_ln78_1_fu_800_p0);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( zext_ln78_3_fu_796_p1 );

    SC_METHOD(thread_mul_ln78_1_fu_800_p1);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( zext_ln78_3_fu_796_p1 );

    SC_METHOD(thread_mul_ln78_1_fu_800_p2);
    sensitive << ( mul_ln78_1_fu_800_p0 );
    sensitive << ( mul_ln78_1_fu_800_p1 );

    SC_METHOD(thread_mul_ln78_fu_790_p0);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( mul_ln78_fu_790_p00 );

    SC_METHOD(thread_mul_ln78_fu_790_p00);
    sensitive << ( sext_ln43_fu_773_p1 );

    SC_METHOD(thread_mul_ln78_fu_790_p1);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( mul_ln78_fu_790_p10 );

    SC_METHOD(thread_mul_ln78_fu_790_p10);
    sensitive << ( sext_ln43_1_fu_776_p1 );

    SC_METHOD(thread_mul_ln78_fu_790_p2);
    sensitive << ( mul_ln78_fu_790_p0 );
    sensitive << ( mul_ln78_fu_790_p1 );

    SC_METHOD(thread_or_ln83_fu_844_p2);
    sensitive << ( icmp_ln83_reg_1226 );
    sensitive << ( icmp_ln83_1_reg_1231 );

    SC_METHOD(thread_output_img_address0);
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( zext_ln84_fu_862_p1 );

    SC_METHOD(thread_output_img_ce0);
    sensitive << ( ap_CS_fsm_state40 );

    SC_METHOD(thread_output_img_d0);
    sensitive << ( and_ln83_reg_1236 );
    sensitive << ( ap_CS_fsm_state40 );

    SC_METHOD(thread_output_img_we0);
    sensitive << ( ap_CS_fsm_state40 );

    SC_METHOD(thread_sext_ln43_1_fu_776_p1);
    sensitive << ( tmp_12_reg_1185 );

    SC_METHOD(thread_sext_ln43_2_fu_779_p1);
    sensitive << ( tmp_13_reg_1191 );

    SC_METHOD(thread_sext_ln43_fu_773_p1);
    sensitive << ( tmp_11_reg_1179 );

    SC_METHOD(thread_sext_ln62_fu_512_p1);
    sensitive << ( ky_0_reg_415 );

    SC_METHOD(thread_sext_ln63_fu_552_p1);
    sensitive << ( kx_0_reg_426 );

    SC_METHOD(thread_sext_ln66_fu_601_p1);
    sensitive << ( add_ln66_1_reg_1055 );

    SC_METHOD(thread_sub_ln66_fu_546_p2);
    sensitive << ( tmp_9_fu_538_p3 );
    sensitive << ( zext_ln66_fu_534_p1 );

    SC_METHOD(thread_sum_1_fu_663_p2);
    sensitive << ( add_ln40_6_fu_658_p2 );
    sensitive << ( add_ln40_2_fu_650_p2 );

    SC_METHOD(thread_sum_3_fu_682_p2);
    sensitive << ( add_ln40_14_fu_677_p2 );
    sensitive << ( add_ln40_10_fu_669_p2 );

    SC_METHOD(thread_sum_5_fu_701_p2);
    sensitive << ( add_ln40_22_fu_696_p2 );
    sensitive << ( add_ln40_18_fu_688_p2 );

    SC_METHOD(thread_tmp_2_fu_818_p4);
    sensitive << ( bitcast_ln83_fu_814_p1 );

    SC_METHOD(thread_tmp_8_fu_854_p3);
    sensitive << ( y_0_reg_391 );
    sensitive << ( x_0_reg_403 );

    SC_METHOD(thread_tmp_9_fu_538_p3);
    sensitive << ( ky_fu_528_p2 );

    SC_METHOD(thread_tmp_s_fu_568_p3);
    sensitive << ( yy_reg_1022 );
    sensitive << ( xx_fu_562_p2 );

    SC_METHOD(thread_trunc_ln83_fu_828_p1);
    sensitive << ( bitcast_ln83_fu_814_p1 );

    SC_METHOD(thread_x_fu_867_p2);
    sensitive << ( x_0_reg_403 );

    SC_METHOD(thread_xx_fu_562_p2);
    sensitive << ( x_0_reg_403 );
    sensitive << ( sext_ln63_fu_552_p1 );

    SC_METHOD(thread_y_fu_506_p2);
    sensitive << ( y_0_reg_391 );

    SC_METHOD(thread_yy_fu_522_p2);
    sensitive << ( y_0_reg_391 );
    sensitive << ( sext_ln62_fu_512_p1 );

    SC_METHOD(thread_zext_ln66_1_fu_575_p1);
    sensitive << ( tmp_s_fu_568_p3 );

    SC_METHOD(thread_zext_ln66_2_fu_587_p1);
    sensitive << ( kx_fu_581_p2 );

    SC_METHOD(thread_zext_ln66_fu_534_p1);
    sensitive << ( ky_fu_528_p2 );

    SC_METHOD(thread_zext_ln78_2_fu_806_p1);
    sensitive << ( mul_ln78_reg_1201 );

    SC_METHOD(thread_zext_ln78_3_fu_796_p1);
    sensitive << ( sext_ln43_2_fu_779_p1 );

    SC_METHOD(thread_zext_ln79_fu_768_p1);
    sensitive << ( add_ln79_fu_764_p2 );

    SC_METHOD(thread_zext_ln84_fu_862_p1);
    sensitive << ( tmp_8_fu_854_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln55_fu_500_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln62_fu_516_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln63_fu_556_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln54_fu_494_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "0000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "HCD_filter_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, I_x_address0, "(port)I_x_address0");
    sc_trace(mVcdFile, I_x_ce0, "(port)I_x_ce0");
    sc_trace(mVcdFile, I_x_q0, "(port)I_x_q0");
    sc_trace(mVcdFile, I_y_address0, "(port)I_y_address0");
    sc_trace(mVcdFile, I_y_ce0, "(port)I_y_ce0");
    sc_trace(mVcdFile, I_y_q0, "(port)I_y_q0");
    sc_trace(mVcdFile, output_img_address0, "(port)output_img_address0");
    sc_trace(mVcdFile, output_img_ce0, "(port)output_img_ce0");
    sc_trace(mVcdFile, output_img_we0, "(port)output_img_we0");
    sc_trace(mVcdFile, output_img_d0, "(port)output_img_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_451_p1, "grp_fu_451_p1");
    sc_trace(mVcdFile, reg_475, "reg_475");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, grp_fu_441_p2, "grp_fu_441_p2");
    sc_trace(mVcdFile, reg_482, "reg_482");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, grp_fu_437_p2, "grp_fu_437_p2");
    sc_trace(mVcdFile, reg_488, "reg_488");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, y_fu_506_p2, "y_fu_506_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln55_fu_500_p2, "icmp_ln55_fu_500_p2");
    sc_trace(mVcdFile, yy_fu_522_p2, "yy_fu_522_p2");
    sc_trace(mVcdFile, yy_reg_1022, "yy_reg_1022");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln62_fu_516_p2, "icmp_ln62_fu_516_p2");
    sc_trace(mVcdFile, ky_fu_528_p2, "ky_fu_528_p2");
    sc_trace(mVcdFile, ky_reg_1027, "ky_reg_1027");
    sc_trace(mVcdFile, sub_ln66_fu_546_p2, "sub_ln66_fu_546_p2");
    sc_trace(mVcdFile, sub_ln66_reg_1032, "sub_ln66_reg_1032");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln63_fu_556_p2, "icmp_ln63_fu_556_p2");
    sc_trace(mVcdFile, kx_fu_581_p2, "kx_fu_581_p2");
    sc_trace(mVcdFile, kx_reg_1050, "kx_reg_1050");
    sc_trace(mVcdFile, add_ln66_1_fu_591_p2, "add_ln66_1_fu_591_p2");
    sc_trace(mVcdFile, add_ln66_1_reg_1055, "add_ln66_1_reg_1055");
    sc_trace(mVcdFile, I_x_load_reg_1060, "I_x_load_reg_1060");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, I_y_load_reg_1067, "I_y_load_reg_1067");
    sc_trace(mVcdFile, grp_fu_457_p2, "grp_fu_457_p2");
    sc_trace(mVcdFile, add_ln40_reg_1074, "add_ln40_reg_1074");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_463_p2, "grp_fu_463_p2");
    sc_trace(mVcdFile, add_ln40_8_reg_1079, "add_ln40_8_reg_1079");
    sc_trace(mVcdFile, grp_fu_469_p2, "grp_fu_469_p2");
    sc_trace(mVcdFile, add_ln40_16_reg_1084, "add_ln40_16_reg_1084");
    sc_trace(mVcdFile, add_ln40_1_reg_1089, "add_ln40_1_reg_1089");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, add_ln40_9_reg_1094, "add_ln40_9_reg_1094");
    sc_trace(mVcdFile, add_ln40_17_reg_1099, "add_ln40_17_reg_1099");
    sc_trace(mVcdFile, Ix2_window_q1, "Ix2_window_q1");
    sc_trace(mVcdFile, Ix2_window_load_3_reg_1104, "Ix2_window_load_3_reg_1104");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, Iy2_window_q1, "Iy2_window_q1");
    sc_trace(mVcdFile, Iy2_window_load_3_reg_1109, "Iy2_window_load_3_reg_1109");
    sc_trace(mVcdFile, Ixy_window_q1, "Ixy_window_q1");
    sc_trace(mVcdFile, Ixy_window_load_3_reg_1114, "Ixy_window_load_3_reg_1114");
    sc_trace(mVcdFile, Ix2_window_q0, "Ix2_window_q0");
    sc_trace(mVcdFile, Ix2_window_load_4_reg_1119, "Ix2_window_load_4_reg_1119");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, Ix2_window_load_5_reg_1124, "Ix2_window_load_5_reg_1124");
    sc_trace(mVcdFile, Iy2_window_q0, "Iy2_window_q0");
    sc_trace(mVcdFile, Iy2_window_load_4_reg_1129, "Iy2_window_load_4_reg_1129");
    sc_trace(mVcdFile, Iy2_window_load_5_reg_1134, "Iy2_window_load_5_reg_1134");
    sc_trace(mVcdFile, Ixy_window_q0, "Ixy_window_q0");
    sc_trace(mVcdFile, Ixy_window_load_4_reg_1139, "Ixy_window_load_4_reg_1139");
    sc_trace(mVcdFile, Ixy_window_load_5_reg_1144, "Ixy_window_load_5_reg_1144");
    sc_trace(mVcdFile, add_ln40_5_fu_623_p2, "add_ln40_5_fu_623_p2");
    sc_trace(mVcdFile, add_ln40_5_reg_1149, "add_ln40_5_reg_1149");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, add_ln40_13_fu_634_p2, "add_ln40_13_fu_634_p2");
    sc_trace(mVcdFile, add_ln40_13_reg_1154, "add_ln40_13_reg_1154");
    sc_trace(mVcdFile, add_ln40_21_fu_645_p2, "add_ln40_21_fu_645_p2");
    sc_trace(mVcdFile, add_ln40_21_reg_1159, "add_ln40_21_reg_1159");
    sc_trace(mVcdFile, sum_1_fu_663_p2, "sum_1_fu_663_p2");
    sc_trace(mVcdFile, sum_1_reg_1164, "sum_1_reg_1164");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, sum_3_fu_682_p2, "sum_3_fu_682_p2");
    sc_trace(mVcdFile, sum_3_reg_1169, "sum_3_reg_1169");
    sc_trace(mVcdFile, sum_5_fu_701_p2, "sum_5_fu_701_p2");
    sc_trace(mVcdFile, sum_5_reg_1174, "sum_5_reg_1174");
    sc_trace(mVcdFile, tmp_11_reg_1179, "tmp_11_reg_1179");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_12_reg_1185, "tmp_12_reg_1185");
    sc_trace(mVcdFile, tmp_13_reg_1191, "tmp_13_reg_1191");
    sc_trace(mVcdFile, zext_ln79_fu_768_p1, "zext_ln79_fu_768_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, mul_ln78_fu_790_p2, "mul_ln78_fu_790_p2");
    sc_trace(mVcdFile, mul_ln78_reg_1201, "mul_ln78_reg_1201");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, mul_ln78_1_fu_800_p2, "mul_ln78_1_fu_800_p2");
    sc_trace(mVcdFile, mul_ln78_1_reg_1206, "mul_ln78_1_reg_1206");
    sc_trace(mVcdFile, zext_ln78_2_fu_806_p1, "zext_ln78_2_fu_806_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, grp_fu_454_p1, "grp_fu_454_p1");
    sc_trace(mVcdFile, tmp_4_reg_1221, "tmp_4_reg_1221");
    sc_trace(mVcdFile, icmp_ln83_fu_832_p2, "icmp_ln83_fu_832_p2");
    sc_trace(mVcdFile, icmp_ln83_reg_1226, "icmp_ln83_reg_1226");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, icmp_ln83_1_fu_838_p2, "icmp_ln83_1_fu_838_p2");
    sc_trace(mVcdFile, icmp_ln83_1_reg_1231, "icmp_ln83_1_reg_1231");
    sc_trace(mVcdFile, and_ln83_fu_848_p2, "and_ln83_fu_848_p2");
    sc_trace(mVcdFile, and_ln83_reg_1236, "and_ln83_reg_1236");
    sc_trace(mVcdFile, ap_CS_fsm_state39, "ap_CS_fsm_state39");
    sc_trace(mVcdFile, x_fu_867_p2, "x_fu_867_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, Ix2_window_address0, "Ix2_window_address0");
    sc_trace(mVcdFile, Ix2_window_ce0, "Ix2_window_ce0");
    sc_trace(mVcdFile, Ix2_window_we0, "Ix2_window_we0");
    sc_trace(mVcdFile, Ix2_window_d0, "Ix2_window_d0");
    sc_trace(mVcdFile, Ix2_window_address1, "Ix2_window_address1");
    sc_trace(mVcdFile, Ix2_window_ce1, "Ix2_window_ce1");
    sc_trace(mVcdFile, Iy2_window_address0, "Iy2_window_address0");
    sc_trace(mVcdFile, Iy2_window_ce0, "Iy2_window_ce0");
    sc_trace(mVcdFile, Iy2_window_we0, "Iy2_window_we0");
    sc_trace(mVcdFile, Iy2_window_d0, "Iy2_window_d0");
    sc_trace(mVcdFile, Iy2_window_address1, "Iy2_window_address1");
    sc_trace(mVcdFile, Iy2_window_ce1, "Iy2_window_ce1");
    sc_trace(mVcdFile, Ixy_window_address0, "Ixy_window_address0");
    sc_trace(mVcdFile, Ixy_window_ce0, "Ixy_window_ce0");
    sc_trace(mVcdFile, Ixy_window_we0, "Ixy_window_we0");
    sc_trace(mVcdFile, Ixy_window_d0, "Ixy_window_d0");
    sc_trace(mVcdFile, Ixy_window_address1, "Ixy_window_address1");
    sc_trace(mVcdFile, Ixy_window_ce1, "Ixy_window_ce1");
    sc_trace(mVcdFile, y_0_reg_391, "y_0_reg_391");
    sc_trace(mVcdFile, x_0_reg_403, "x_0_reg_403");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln54_fu_494_p2, "icmp_ln54_fu_494_p2");
    sc_trace(mVcdFile, ky_0_reg_415, "ky_0_reg_415");
    sc_trace(mVcdFile, kx_0_reg_426, "kx_0_reg_426");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln66_1_fu_575_p1, "zext_ln66_1_fu_575_p1");
    sc_trace(mVcdFile, sext_ln66_fu_601_p1, "sext_ln66_fu_601_p1");
    sc_trace(mVcdFile, zext_ln84_fu_862_p1, "zext_ln84_fu_862_p1");
    sc_trace(mVcdFile, grp_fu_437_p0, "grp_fu_437_p0");
    sc_trace(mVcdFile, grp_fu_437_p1, "grp_fu_437_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, grp_fu_441_p0, "grp_fu_441_p0");
    sc_trace(mVcdFile, grp_fu_441_p1, "grp_fu_441_p1");
    sc_trace(mVcdFile, grp_fu_451_p0, "grp_fu_451_p0");
    sc_trace(mVcdFile, grp_fu_454_p0, "grp_fu_454_p0");
    sc_trace(mVcdFile, sext_ln62_fu_512_p1, "sext_ln62_fu_512_p1");
    sc_trace(mVcdFile, tmp_9_fu_538_p3, "tmp_9_fu_538_p3");
    sc_trace(mVcdFile, zext_ln66_fu_534_p1, "zext_ln66_fu_534_p1");
    sc_trace(mVcdFile, sext_ln63_fu_552_p1, "sext_ln63_fu_552_p1");
    sc_trace(mVcdFile, xx_fu_562_p2, "xx_fu_562_p2");
    sc_trace(mVcdFile, tmp_s_fu_568_p3, "tmp_s_fu_568_p3");
    sc_trace(mVcdFile, zext_ln66_2_fu_587_p1, "zext_ln66_2_fu_587_p1");
    sc_trace(mVcdFile, add_ln40_4_fu_617_p2, "add_ln40_4_fu_617_p2");
    sc_trace(mVcdFile, add_ln40_12_fu_628_p2, "add_ln40_12_fu_628_p2");
    sc_trace(mVcdFile, add_ln40_20_fu_639_p2, "add_ln40_20_fu_639_p2");
    sc_trace(mVcdFile, add_ln40_3_fu_654_p2, "add_ln40_3_fu_654_p2");
    sc_trace(mVcdFile, add_ln40_6_fu_658_p2, "add_ln40_6_fu_658_p2");
    sc_trace(mVcdFile, add_ln40_2_fu_650_p2, "add_ln40_2_fu_650_p2");
    sc_trace(mVcdFile, add_ln40_11_fu_673_p2, "add_ln40_11_fu_673_p2");
    sc_trace(mVcdFile, add_ln40_14_fu_677_p2, "add_ln40_14_fu_677_p2");
    sc_trace(mVcdFile, add_ln40_10_fu_669_p2, "add_ln40_10_fu_669_p2");
    sc_trace(mVcdFile, add_ln40_19_fu_692_p2, "add_ln40_19_fu_692_p2");
    sc_trace(mVcdFile, add_ln40_22_fu_696_p2, "add_ln40_22_fu_696_p2");
    sc_trace(mVcdFile, add_ln40_18_fu_688_p2, "add_ln40_18_fu_688_p2");
    sc_trace(mVcdFile, mul_ln43_fu_710_p1, "mul_ln43_fu_710_p1");
    sc_trace(mVcdFile, mul_ln43_fu_710_p2, "mul_ln43_fu_710_p2");
    sc_trace(mVcdFile, mul_ln43_1_fu_729_p1, "mul_ln43_1_fu_729_p1");
    sc_trace(mVcdFile, mul_ln43_1_fu_729_p2, "mul_ln43_1_fu_729_p2");
    sc_trace(mVcdFile, mul_ln43_2_fu_748_p1, "mul_ln43_2_fu_748_p1");
    sc_trace(mVcdFile, mul_ln43_2_fu_748_p2, "mul_ln43_2_fu_748_p2");
    sc_trace(mVcdFile, add_ln79_fu_764_p2, "add_ln79_fu_764_p2");
    sc_trace(mVcdFile, sext_ln43_fu_773_p1, "sext_ln43_fu_773_p1");
    sc_trace(mVcdFile, sext_ln43_1_fu_776_p1, "sext_ln43_1_fu_776_p1");
    sc_trace(mVcdFile, mul_ln78_fu_790_p0, "mul_ln78_fu_790_p0");
    sc_trace(mVcdFile, mul_ln78_fu_790_p1, "mul_ln78_fu_790_p1");
    sc_trace(mVcdFile, sext_ln43_2_fu_779_p1, "sext_ln43_2_fu_779_p1");
    sc_trace(mVcdFile, mul_ln78_1_fu_800_p0, "mul_ln78_1_fu_800_p0");
    sc_trace(mVcdFile, zext_ln78_3_fu_796_p1, "zext_ln78_3_fu_796_p1");
    sc_trace(mVcdFile, mul_ln78_1_fu_800_p1, "mul_ln78_1_fu_800_p1");
    sc_trace(mVcdFile, bitcast_ln83_fu_814_p1, "bitcast_ln83_fu_814_p1");
    sc_trace(mVcdFile, tmp_2_fu_818_p4, "tmp_2_fu_818_p4");
    sc_trace(mVcdFile, trunc_ln83_fu_828_p1, "trunc_ln83_fu_828_p1");
    sc_trace(mVcdFile, or_ln83_fu_844_p2, "or_ln83_fu_844_p2");
    sc_trace(mVcdFile, grp_fu_446_p2, "grp_fu_446_p2");
    sc_trace(mVcdFile, tmp_8_fu_854_p3, "tmp_8_fu_854_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln43_1_fu_729_p10, "mul_ln43_1_fu_729_p10");
    sc_trace(mVcdFile, mul_ln43_2_fu_748_p10, "mul_ln43_2_fu_748_p10");
    sc_trace(mVcdFile, mul_ln43_fu_710_p10, "mul_ln43_fu_710_p10");
    sc_trace(mVcdFile, mul_ln78_fu_790_p00, "mul_ln78_fu_790_p00");
    sc_trace(mVcdFile, mul_ln78_fu_790_p10, "mul_ln78_fu_790_p10");
#endif

    }
}

HCD_filter_hw::~HCD_filter_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete Ix2_window_U;
    delete Iy2_window_U;
    delete Ixy_window_U;
    delete HLS_accel_dsub_64eOg_U2;
    delete HLS_accel_dmul_64fYi_U3;
    delete HLS_accel_dcmp_64g8j_U4;
    delete HLS_accel_sitodp_hbi_U5;
    delete HLS_accel_sitodp_hbi_U6;
}

void HCD_filter_hw::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void HCD_filter_hw::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_407F400000000000;
}

void HCD_filter_hw::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_2;
}

void HCD_filter_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        kx_0_reg_426 = kx_reg_1050.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln62_fu_516_p2.read(), ap_const_lv1_0))) {
        kx_0_reg_426 = ap_const_lv3_7;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_556_p2.read()))) {
        ky_0_reg_415 = ky_reg_1027.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln55_fu_500_p2.read(), ap_const_lv1_0))) {
        ky_0_reg_415 = ap_const_lv3_7;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_494_p2.read()))) {
        x_0_reg_403 = ap_const_lv8_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        x_0_reg_403 = x_fu_867_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_500_p2.read(), ap_const_lv1_1))) {
        y_0_reg_391 = y_fu_506_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        y_0_reg_391 = ap_const_lv8_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        I_x_load_reg_1060 = I_x_q0.read();
        I_y_load_reg_1067 = I_y_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Ix2_window_load_3_reg_1104 = Ix2_window_q1.read();
        Ixy_window_load_3_reg_1114 = Ixy_window_q1.read();
        Iy2_window_load_3_reg_1109 = Iy2_window_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Ix2_window_load_4_reg_1119 = Ix2_window_q0.read();
        Ix2_window_load_5_reg_1124 = Ix2_window_q1.read();
        Ixy_window_load_4_reg_1139 = Ixy_window_q0.read();
        Ixy_window_load_5_reg_1144 = Ixy_window_q1.read();
        Iy2_window_load_4_reg_1129 = Iy2_window_q0.read();
        Iy2_window_load_5_reg_1134 = Iy2_window_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        add_ln40_13_reg_1154 = add_ln40_13_fu_634_p2.read();
        add_ln40_21_reg_1159 = add_ln40_21_fu_645_p2.read();
        add_ln40_5_reg_1149 = add_ln40_5_fu_623_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        add_ln40_16_reg_1084 = grp_fu_469_p2.read();
        add_ln40_8_reg_1079 = grp_fu_463_p2.read();
        add_ln40_reg_1074 = grp_fu_457_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln40_17_reg_1099 = grp_fu_469_p2.read();
        add_ln40_1_reg_1089 = grp_fu_457_p2.read();
        add_ln40_9_reg_1094 = grp_fu_463_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_556_p2.read()))) {
        add_ln66_1_reg_1055 = add_ln66_1_fu_591_p2.read();
        kx_reg_1050 = kx_fu_581_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        and_ln83_reg_1236 = and_ln83_fu_848_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        icmp_ln83_1_reg_1231 = icmp_ln83_1_fu_838_p2.read();
        icmp_ln83_reg_1226 = icmp_ln83_fu_832_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln62_fu_516_p2.read(), ap_const_lv1_0))) {
        ky_reg_1027 = ky_fu_528_p2.read();
        sub_ln66_reg_1032 = sub_ln66_fu_546_p2.read();
        yy_reg_1022 = yy_fu_522_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        mul_ln78_1_reg_1206 = mul_ln78_1_fu_800_p2.read();
        mul_ln78_reg_1201 = mul_ln78_fu_790_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()))) {
        reg_475 = grp_fu_451_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()))) {
        reg_482 = grp_fu_441_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read()))) {
        reg_488 = grp_fu_437_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        sum_1_reg_1164 = sum_1_fu_663_p2.read();
        sum_3_reg_1169 = sum_3_fu_682_p2.read();
        sum_5_reg_1174 = sum_5_fu_701_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        tmp_11_reg_1179 = mul_ln43_fu_710_p2.read().range(17, 12);
        tmp_12_reg_1185 = mul_ln43_1_fu_729_p2.read().range(17, 12);
        tmp_13_reg_1191 = mul_ln43_2_fu_748_p2.read().range(17, 12);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        tmp_4_reg_1221 = grp_fu_454_p1.read();
    }
}

void HCD_filter_hw::thread_I_x_address0() {
    I_x_address0 =  (sc_lv<16>) (zext_ln66_1_fu_575_p1.read());
}

void HCD_filter_hw::thread_I_x_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        I_x_ce0 = ap_const_logic_1;
    } else {
        I_x_ce0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_I_y_address0() {
    I_y_address0 =  (sc_lv<16>) (zext_ln66_1_fu_575_p1.read());
}

void HCD_filter_hw::thread_I_y_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        I_y_ce0 = ap_const_logic_1;
    } else {
        I_y_ce0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Ix2_window_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Ix2_window_address0 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Ix2_window_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Ix2_window_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Ix2_window_address0 =  (sc_lv<4>) (sext_ln66_fu_601_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Ix2_window_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        Ix2_window_address0 = "XXXX";
    }
}

void HCD_filter_hw::thread_Ix2_window_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Ix2_window_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Ix2_window_address1 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Ix2_window_address1 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Ix2_window_address1 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Ix2_window_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        Ix2_window_address1 = "XXXX";
    }
}

void HCD_filter_hw::thread_Ix2_window_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        Ix2_window_ce0 = ap_const_logic_1;
    } else {
        Ix2_window_ce0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Ix2_window_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        Ix2_window_ce1 = ap_const_logic_1;
    } else {
        Ix2_window_ce1 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Ix2_window_d0() {
    Ix2_window_d0 = (!I_x_load_reg_1060.read().is_01() || !I_x_load_reg_1060.read().is_01())? sc_lv<8>(): sc_bigint<8>(I_x_load_reg_1060.read()) * sc_bigint<8>(I_x_load_reg_1060.read());
}

void HCD_filter_hw::thread_Ix2_window_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Ix2_window_we0 = ap_const_logic_1;
    } else {
        Ix2_window_we0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Ixy_window_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Ixy_window_address0 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Ixy_window_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Ixy_window_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Ixy_window_address0 =  (sc_lv<4>) (sext_ln66_fu_601_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Ixy_window_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        Ixy_window_address0 = "XXXX";
    }
}

void HCD_filter_hw::thread_Ixy_window_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Ixy_window_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Ixy_window_address1 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Ixy_window_address1 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Ixy_window_address1 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Ixy_window_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        Ixy_window_address1 = "XXXX";
    }
}

void HCD_filter_hw::thread_Ixy_window_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        Ixy_window_ce0 = ap_const_logic_1;
    } else {
        Ixy_window_ce0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Ixy_window_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        Ixy_window_ce1 = ap_const_logic_1;
    } else {
        Ixy_window_ce1 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Ixy_window_d0() {
    Ixy_window_d0 = (!I_y_load_reg_1067.read().is_01() || !I_x_load_reg_1060.read().is_01())? sc_lv<8>(): sc_bigint<8>(I_y_load_reg_1067.read()) * sc_bigint<8>(I_x_load_reg_1060.read());
}

void HCD_filter_hw::thread_Ixy_window_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Ixy_window_we0 = ap_const_logic_1;
    } else {
        Ixy_window_we0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Iy2_window_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Iy2_window_address0 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Iy2_window_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Iy2_window_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Iy2_window_address0 =  (sc_lv<4>) (sext_ln66_fu_601_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Iy2_window_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        Iy2_window_address0 = "XXXX";
    }
}

void HCD_filter_hw::thread_Iy2_window_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Iy2_window_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Iy2_window_address1 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Iy2_window_address1 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Iy2_window_address1 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Iy2_window_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        Iy2_window_address1 = "XXXX";
    }
}

void HCD_filter_hw::thread_Iy2_window_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        Iy2_window_ce0 = ap_const_logic_1;
    } else {
        Iy2_window_ce0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Iy2_window_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        Iy2_window_ce1 = ap_const_logic_1;
    } else {
        Iy2_window_ce1 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_Iy2_window_d0() {
    Iy2_window_d0 = (!I_y_load_reg_1067.read().is_01() || !I_y_load_reg_1067.read().is_01())? sc_lv<8>(): sc_bigint<8>(I_y_load_reg_1067.read()) * sc_bigint<8>(I_y_load_reg_1067.read());
}

void HCD_filter_hw::thread_Iy2_window_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Iy2_window_we0 = ap_const_logic_1;
    } else {
        Iy2_window_we0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_add_ln40_10_fu_669_p2() {
    add_ln40_10_fu_669_p2 = (!add_ln40_9_reg_1094.read().is_01() || !add_ln40_8_reg_1079.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_9_reg_1094.read()) + sc_biguint<8>(add_ln40_8_reg_1079.read()));
}

void HCD_filter_hw::thread_add_ln40_11_fu_673_p2() {
    add_ln40_11_fu_673_p2 = (!Iy2_window_load_3_reg_1109.read().is_01() || !Iy2_window_load_4_reg_1129.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Iy2_window_load_3_reg_1109.read()) + sc_biguint<8>(Iy2_window_load_4_reg_1129.read()));
}

void HCD_filter_hw::thread_add_ln40_12_fu_628_p2() {
    add_ln40_12_fu_628_p2 = (!Iy2_window_q0.read().is_01() || !Iy2_window_q1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Iy2_window_q0.read()) + sc_biguint<8>(Iy2_window_q1.read()));
}

void HCD_filter_hw::thread_add_ln40_13_fu_634_p2() {
    add_ln40_13_fu_634_p2 = (!add_ln40_12_fu_628_p2.read().is_01() || !Iy2_window_load_5_reg_1134.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_12_fu_628_p2.read()) + sc_biguint<8>(Iy2_window_load_5_reg_1134.read()));
}

void HCD_filter_hw::thread_add_ln40_14_fu_677_p2() {
    add_ln40_14_fu_677_p2 = (!add_ln40_13_reg_1154.read().is_01() || !add_ln40_11_fu_673_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_13_reg_1154.read()) + sc_biguint<8>(add_ln40_11_fu_673_p2.read()));
}

void HCD_filter_hw::thread_add_ln40_18_fu_688_p2() {
    add_ln40_18_fu_688_p2 = (!add_ln40_17_reg_1099.read().is_01() || !add_ln40_16_reg_1084.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_17_reg_1099.read()) + sc_biguint<8>(add_ln40_16_reg_1084.read()));
}

void HCD_filter_hw::thread_add_ln40_19_fu_692_p2() {
    add_ln40_19_fu_692_p2 = (!Ixy_window_load_3_reg_1114.read().is_01() || !Ixy_window_load_4_reg_1139.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Ixy_window_load_3_reg_1114.read()) + sc_biguint<8>(Ixy_window_load_4_reg_1139.read()));
}

void HCD_filter_hw::thread_add_ln40_20_fu_639_p2() {
    add_ln40_20_fu_639_p2 = (!Ixy_window_q0.read().is_01() || !Ixy_window_q1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Ixy_window_q0.read()) + sc_biguint<8>(Ixy_window_q1.read()));
}

void HCD_filter_hw::thread_add_ln40_21_fu_645_p2() {
    add_ln40_21_fu_645_p2 = (!add_ln40_20_fu_639_p2.read().is_01() || !Ixy_window_load_5_reg_1144.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_20_fu_639_p2.read()) + sc_biguint<8>(Ixy_window_load_5_reg_1144.read()));
}

void HCD_filter_hw::thread_add_ln40_22_fu_696_p2() {
    add_ln40_22_fu_696_p2 = (!add_ln40_21_reg_1159.read().is_01() || !add_ln40_19_fu_692_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_21_reg_1159.read()) + sc_biguint<8>(add_ln40_19_fu_692_p2.read()));
}

void HCD_filter_hw::thread_add_ln40_2_fu_650_p2() {
    add_ln40_2_fu_650_p2 = (!add_ln40_1_reg_1089.read().is_01() || !add_ln40_reg_1074.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_1_reg_1089.read()) + sc_biguint<8>(add_ln40_reg_1074.read()));
}

void HCD_filter_hw::thread_add_ln40_3_fu_654_p2() {
    add_ln40_3_fu_654_p2 = (!Ix2_window_load_3_reg_1104.read().is_01() || !Ix2_window_load_4_reg_1119.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Ix2_window_load_3_reg_1104.read()) + sc_biguint<8>(Ix2_window_load_4_reg_1119.read()));
}

void HCD_filter_hw::thread_add_ln40_4_fu_617_p2() {
    add_ln40_4_fu_617_p2 = (!Ix2_window_q0.read().is_01() || !Ix2_window_q1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Ix2_window_q0.read()) + sc_biguint<8>(Ix2_window_q1.read()));
}

void HCD_filter_hw::thread_add_ln40_5_fu_623_p2() {
    add_ln40_5_fu_623_p2 = (!add_ln40_4_fu_617_p2.read().is_01() || !Ix2_window_load_5_reg_1124.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_4_fu_617_p2.read()) + sc_biguint<8>(Ix2_window_load_5_reg_1124.read()));
}

void HCD_filter_hw::thread_add_ln40_6_fu_658_p2() {
    add_ln40_6_fu_658_p2 = (!add_ln40_5_reg_1149.read().is_01() || !add_ln40_3_fu_654_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_5_reg_1149.read()) + sc_biguint<8>(add_ln40_3_fu_654_p2.read()));
}

void HCD_filter_hw::thread_add_ln66_1_fu_591_p2() {
    add_ln66_1_fu_591_p2 = (!sub_ln66_reg_1032.read().is_01() || !zext_ln66_2_fu_587_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(sub_ln66_reg_1032.read()) + sc_biguint<5>(zext_ln66_2_fu_587_p1.read()));
}

void HCD_filter_hw::thread_add_ln79_fu_764_p2() {
    add_ln79_fu_764_p2 = (!tmp_11_reg_1179.read().is_01() || !tmp_12_reg_1185.read().is_01())? sc_lv<6>(): (sc_bigint<6>(tmp_11_reg_1179.read()) + sc_bigint<6>(tmp_12_reg_1185.read()));
}

void HCD_filter_hw::thread_and_ln83_fu_848_p2() {
    and_ln83_fu_848_p2 = (or_ln83_fu_844_p2.read() & grp_fu_446_p2.read());
}

void HCD_filter_hw::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void HCD_filter_hw::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void HCD_filter_hw::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void HCD_filter_hw::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void HCD_filter_hw::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void HCD_filter_hw::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void HCD_filter_hw::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void HCD_filter_hw::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void HCD_filter_hw::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void HCD_filter_hw::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void HCD_filter_hw::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void HCD_filter_hw::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void HCD_filter_hw::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void HCD_filter_hw::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void HCD_filter_hw::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void HCD_filter_hw::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void HCD_filter_hw::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void HCD_filter_hw::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void HCD_filter_hw::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void HCD_filter_hw::thread_ap_CS_fsm_state39() {
    ap_CS_fsm_state39 = ap_CS_fsm.read()[38];
}

void HCD_filter_hw::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void HCD_filter_hw::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void HCD_filter_hw::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void HCD_filter_hw::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void HCD_filter_hw::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void HCD_filter_hw::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void HCD_filter_hw::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void HCD_filter_hw::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln54_fu_494_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln54_fu_494_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_bitcast_ln83_fu_814_p1() {
    bitcast_ln83_fu_814_p1 = reg_488.read();
}

void HCD_filter_hw::thread_grp_fu_437_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        grp_fu_437_p0 = reg_488.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        grp_fu_437_p0 = reg_475.read();
    } else {
        grp_fu_437_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void HCD_filter_hw::thread_grp_fu_437_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        grp_fu_437_p1 = reg_482.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        grp_fu_437_p1 = tmp_4_reg_1221.read();
    } else {
        grp_fu_437_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void HCD_filter_hw::thread_grp_fu_441_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_441_p0 = reg_482.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_441_p0 = reg_475.read();
    } else {
        grp_fu_441_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void HCD_filter_hw::thread_grp_fu_441_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_441_p1 = ap_const_lv64_3FA47AE147AE147B;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_441_p1 = reg_475.read();
    } else {
        grp_fu_441_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void HCD_filter_hw::thread_grp_fu_451_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_fu_451_p0 = zext_ln78_2_fu_806_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_451_p0 = zext_ln79_fu_768_p1.read();
    } else {
        grp_fu_451_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void HCD_filter_hw::thread_grp_fu_454_p0() {
    grp_fu_454_p0 = esl_zext<32,16>(mul_ln78_1_reg_1206.read());
}

void HCD_filter_hw::thread_grp_fu_457_p2() {
    grp_fu_457_p2 = (!Ix2_window_q1.read().is_01() || !Ix2_window_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Ix2_window_q1.read()) + sc_biguint<8>(Ix2_window_q0.read()));
}

void HCD_filter_hw::thread_grp_fu_463_p2() {
    grp_fu_463_p2 = (!Iy2_window_q1.read().is_01() || !Iy2_window_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Iy2_window_q1.read()) + sc_biguint<8>(Iy2_window_q0.read()));
}

void HCD_filter_hw::thread_grp_fu_469_p2() {
    grp_fu_469_p2 = (!Ixy_window_q1.read().is_01() || !Ixy_window_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(Ixy_window_q1.read()) + sc_biguint<8>(Ixy_window_q0.read()));
}

void HCD_filter_hw::thread_icmp_ln54_fu_494_p2() {
    icmp_ln54_fu_494_p2 = (!y_0_reg_391.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_391.read() == ap_const_lv8_FF);
}

void HCD_filter_hw::thread_icmp_ln55_fu_500_p2() {
    icmp_ln55_fu_500_p2 = (!x_0_reg_403.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_403.read() == ap_const_lv8_FF);
}

void HCD_filter_hw::thread_icmp_ln62_fu_516_p2() {
    icmp_ln62_fu_516_p2 = (!ky_0_reg_415.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<1>(): sc_lv<1>(ky_0_reg_415.read() == ap_const_lv3_2);
}

void HCD_filter_hw::thread_icmp_ln63_fu_556_p2() {
    icmp_ln63_fu_556_p2 = (!kx_0_reg_426.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<1>(): sc_lv<1>(kx_0_reg_426.read() == ap_const_lv3_2);
}

void HCD_filter_hw::thread_icmp_ln83_1_fu_838_p2() {
    icmp_ln83_1_fu_838_p2 = (!trunc_ln83_fu_828_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln83_fu_828_p1.read() == ap_const_lv52_0);
}

void HCD_filter_hw::thread_icmp_ln83_fu_832_p2() {
    icmp_ln83_fu_832_p2 = (!tmp_2_fu_818_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_818_p4.read() != ap_const_lv11_7FF);
}

void HCD_filter_hw::thread_kx_fu_581_p2() {
    kx_fu_581_p2 = (!kx_0_reg_426.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_bigint<3>(kx_0_reg_426.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void HCD_filter_hw::thread_ky_fu_528_p2() {
    ky_fu_528_p2 = (!ky_0_reg_415.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_bigint<3>(ky_0_reg_415.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void HCD_filter_hw::thread_mul_ln43_1_fu_729_p1() {
    mul_ln43_1_fu_729_p1 =  (sc_lv<8>) (mul_ln43_1_fu_729_p10.read());
}

void HCD_filter_hw::thread_mul_ln43_1_fu_729_p10() {
    mul_ln43_1_fu_729_p10 = esl_zext<18,8>(sum_3_reg_1169.read());
}

void HCD_filter_hw::thread_mul_ln43_1_fu_729_p2() {
    mul_ln43_1_fu_729_p2 = (!ap_const_lv18_1C8.is_01() || !mul_ln43_1_fu_729_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_1C8) * sc_biguint<8>(mul_ln43_1_fu_729_p1.read());
}

void HCD_filter_hw::thread_mul_ln43_2_fu_748_p1() {
    mul_ln43_2_fu_748_p1 =  (sc_lv<8>) (mul_ln43_2_fu_748_p10.read());
}

void HCD_filter_hw::thread_mul_ln43_2_fu_748_p10() {
    mul_ln43_2_fu_748_p10 = esl_zext<18,8>(sum_5_reg_1174.read());
}

void HCD_filter_hw::thread_mul_ln43_2_fu_748_p2() {
    mul_ln43_2_fu_748_p2 = (!ap_const_lv18_1C8.is_01() || !mul_ln43_2_fu_748_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_1C8) * sc_biguint<8>(mul_ln43_2_fu_748_p1.read());
}

void HCD_filter_hw::thread_mul_ln43_fu_710_p1() {
    mul_ln43_fu_710_p1 =  (sc_lv<8>) (mul_ln43_fu_710_p10.read());
}

void HCD_filter_hw::thread_mul_ln43_fu_710_p10() {
    mul_ln43_fu_710_p10 = esl_zext<18,8>(sum_1_reg_1164.read());
}

void HCD_filter_hw::thread_mul_ln43_fu_710_p2() {
    mul_ln43_fu_710_p2 = (!ap_const_lv18_1C8.is_01() || !mul_ln43_fu_710_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_1C8) * sc_biguint<8>(mul_ln43_fu_710_p1.read());
}

void HCD_filter_hw::thread_mul_ln78_1_fu_800_p0() {
    mul_ln78_1_fu_800_p0 =  (sc_lv<8>) (zext_ln78_3_fu_796_p1.read());
}

void HCD_filter_hw::thread_mul_ln78_1_fu_800_p1() {
    mul_ln78_1_fu_800_p1 =  (sc_lv<8>) (zext_ln78_3_fu_796_p1.read());
}

void HCD_filter_hw::thread_mul_ln78_1_fu_800_p2() {
    mul_ln78_1_fu_800_p2 = (!mul_ln78_1_fu_800_p0.read().is_01() || !mul_ln78_1_fu_800_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(mul_ln78_1_fu_800_p0.read()) * sc_biguint<8>(mul_ln78_1_fu_800_p1.read());
}

void HCD_filter_hw::thread_mul_ln78_fu_790_p0() {
    mul_ln78_fu_790_p0 =  (sc_lv<8>) (mul_ln78_fu_790_p00.read());
}

void HCD_filter_hw::thread_mul_ln78_fu_790_p00() {
    mul_ln78_fu_790_p00 = esl_zext<16,8>(sext_ln43_fu_773_p1.read());
}

void HCD_filter_hw::thread_mul_ln78_fu_790_p1() {
    mul_ln78_fu_790_p1 =  (sc_lv<8>) (mul_ln78_fu_790_p10.read());
}

void HCD_filter_hw::thread_mul_ln78_fu_790_p10() {
    mul_ln78_fu_790_p10 = esl_zext<16,8>(sext_ln43_1_fu_776_p1.read());
}

void HCD_filter_hw::thread_mul_ln78_fu_790_p2() {
    mul_ln78_fu_790_p2 = (!mul_ln78_fu_790_p0.read().is_01() || !mul_ln78_fu_790_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(mul_ln78_fu_790_p0.read()) * sc_biguint<8>(mul_ln78_fu_790_p1.read());
}

void HCD_filter_hw::thread_or_ln83_fu_844_p2() {
    or_ln83_fu_844_p2 = (icmp_ln83_1_reg_1231.read() | icmp_ln83_reg_1226.read());
}

void HCD_filter_hw::thread_output_img_address0() {
    output_img_address0 =  (sc_lv<16>) (zext_ln84_fu_862_p1.read());
}

void HCD_filter_hw::thread_output_img_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        output_img_ce0 = ap_const_logic_1;
    } else {
        output_img_ce0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_output_img_d0() {
    output_img_d0 = and_ln83_reg_1236.read();
}

void HCD_filter_hw::thread_output_img_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        output_img_we0 = ap_const_logic_1;
    } else {
        output_img_we0 = ap_const_logic_0;
    }
}

void HCD_filter_hw::thread_sext_ln43_1_fu_776_p1() {
    sext_ln43_1_fu_776_p1 = esl_sext<8,6>(tmp_12_reg_1185.read());
}

void HCD_filter_hw::thread_sext_ln43_2_fu_779_p1() {
    sext_ln43_2_fu_779_p1 = esl_sext<8,6>(tmp_13_reg_1191.read());
}

void HCD_filter_hw::thread_sext_ln43_fu_773_p1() {
    sext_ln43_fu_773_p1 = esl_sext<8,6>(tmp_11_reg_1179.read());
}

void HCD_filter_hw::thread_sext_ln62_fu_512_p1() {
    sext_ln62_fu_512_p1 = esl_sext<8,3>(ky_0_reg_415.read());
}

void HCD_filter_hw::thread_sext_ln63_fu_552_p1() {
    sext_ln63_fu_552_p1 = esl_sext<8,3>(kx_0_reg_426.read());
}

void HCD_filter_hw::thread_sext_ln66_fu_601_p1() {
    sext_ln66_fu_601_p1 = esl_sext<64,5>(add_ln66_1_reg_1055.read());
}

void HCD_filter_hw::thread_sub_ln66_fu_546_p2() {
    sub_ln66_fu_546_p2 = (!tmp_9_fu_538_p3.read().is_01() || !zext_ln66_fu_534_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_9_fu_538_p3.read()) - sc_biguint<5>(zext_ln66_fu_534_p1.read()));
}

void HCD_filter_hw::thread_sum_1_fu_663_p2() {
    sum_1_fu_663_p2 = (!add_ln40_6_fu_658_p2.read().is_01() || !add_ln40_2_fu_650_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_6_fu_658_p2.read()) + sc_biguint<8>(add_ln40_2_fu_650_p2.read()));
}

void HCD_filter_hw::thread_sum_3_fu_682_p2() {
    sum_3_fu_682_p2 = (!add_ln40_14_fu_677_p2.read().is_01() || !add_ln40_10_fu_669_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_14_fu_677_p2.read()) + sc_biguint<8>(add_ln40_10_fu_669_p2.read()));
}

void HCD_filter_hw::thread_sum_5_fu_701_p2() {
    sum_5_fu_701_p2 = (!add_ln40_22_fu_696_p2.read().is_01() || !add_ln40_18_fu_688_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln40_22_fu_696_p2.read()) + sc_biguint<8>(add_ln40_18_fu_688_p2.read()));
}

void HCD_filter_hw::thread_tmp_2_fu_818_p4() {
    tmp_2_fu_818_p4 = bitcast_ln83_fu_814_p1.read().range(62, 52);
}

void HCD_filter_hw::thread_tmp_8_fu_854_p3() {
    tmp_8_fu_854_p3 = esl_concat<8,8>(y_0_reg_391.read(), x_0_reg_403.read());
}

void HCD_filter_hw::thread_tmp_9_fu_538_p3() {
    tmp_9_fu_538_p3 = esl_concat<3,2>(ky_fu_528_p2.read(), ap_const_lv2_0);
}

void HCD_filter_hw::thread_tmp_s_fu_568_p3() {
    tmp_s_fu_568_p3 = esl_concat<8,8>(yy_reg_1022.read(), xx_fu_562_p2.read());
}

void HCD_filter_hw::thread_trunc_ln83_fu_828_p1() {
    trunc_ln83_fu_828_p1 = bitcast_ln83_fu_814_p1.read().range(52-1, 0);
}

void HCD_filter_hw::thread_x_fu_867_p2() {
    x_fu_867_p2 = (!ap_const_lv8_1.is_01() || !x_0_reg_403.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(x_0_reg_403.read()));
}

void HCD_filter_hw::thread_xx_fu_562_p2() {
    xx_fu_562_p2 = (!sext_ln63_fu_552_p1.read().is_01() || !x_0_reg_403.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sext_ln63_fu_552_p1.read()) + sc_biguint<8>(x_0_reg_403.read()));
}

void HCD_filter_hw::thread_y_fu_506_p2() {
    y_fu_506_p2 = (!y_0_reg_391.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(y_0_reg_391.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void HCD_filter_hw::thread_yy_fu_522_p2() {
    yy_fu_522_p2 = (!sext_ln62_fu_512_p1.read().is_01() || !y_0_reg_391.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sext_ln62_fu_512_p1.read()) + sc_biguint<8>(y_0_reg_391.read()));
}

void HCD_filter_hw::thread_zext_ln66_1_fu_575_p1() {
    zext_ln66_1_fu_575_p1 = esl_zext<64,16>(tmp_s_fu_568_p3.read());
}

void HCD_filter_hw::thread_zext_ln66_2_fu_587_p1() {
    zext_ln66_2_fu_587_p1 = esl_zext<5,3>(kx_fu_581_p2.read());
}

void HCD_filter_hw::thread_zext_ln66_fu_534_p1() {
    zext_ln66_fu_534_p1 = esl_zext<5,3>(ky_fu_528_p2.read());
}

void HCD_filter_hw::thread_zext_ln78_2_fu_806_p1() {
    zext_ln78_2_fu_806_p1 = esl_zext<32,16>(mul_ln78_reg_1201.read());
}

void HCD_filter_hw::thread_zext_ln78_3_fu_796_p1() {
    zext_ln78_3_fu_796_p1 = esl_zext<16,8>(sext_ln43_2_fu_779_p1.read());
}

void HCD_filter_hw::thread_zext_ln79_fu_768_p1() {
    zext_ln79_fu_768_p1 = esl_zext<32,6>(add_ln79_fu_764_p2.read());
}

void HCD_filter_hw::thread_zext_ln84_fu_862_p1() {
    zext_ln84_fu_862_p1 = esl_zext<64,16>(tmp_8_fu_854_p3.read());
}

void HCD_filter_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln54_fu_494_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln55_fu_500_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln62_fu_516_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_556_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<40>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

