// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "HLS_accel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic HLS_accel::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic HLS_accel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> HLS_accel::ap_ST_fsm_state1 = "1";
const sc_lv<4> HLS_accel::ap_ST_fsm_state2 = "10";
const sc_lv<4> HLS_accel::ap_ST_fsm_state3 = "100";
const sc_lv<4> HLS_accel::ap_ST_fsm_state4 = "1000";
const sc_lv<32> HLS_accel::ap_const_lv32_0 = "00000000000000000000000000000000";
const int HLS_accel::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> HLS_accel::ap_const_lv32_1 = "1";
const sc_lv<32> HLS_accel::ap_const_lv32_2 = "10";
const sc_lv<32> HLS_accel::ap_const_lv32_3 = "11";
const bool HLS_accel::ap_const_boolean_1 = true;

HLS_accel::HLS_accel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    HLS_accel_CONTROL_BUS_s_axi_U = new HLS_accel_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("HLS_accel_CONTROL_BUS_s_axi_U");
    HLS_accel_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    HLS_accel_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    HLS_accel_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    HLS_accel_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    HLS_accel_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    HLS_accel_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    HLS_accel_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    HLS_accel_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    HLS_accel_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    HLS_accel_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    HLS_accel_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    HLS_accel_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    HLS_accel_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    HLS_accel_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    HLS_accel_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    HLS_accel_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    HLS_accel_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    HLS_accel_CONTROL_BUS_s_axi_U->ACLK(ap_clk);
    HLS_accel_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    HLS_accel_CONTROL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    HLS_accel_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    HLS_accel_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    HLS_accel_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    HLS_accel_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    HLS_accel_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    grp_wrapped_HCD_filter_h_fu_52 = new wrapped_HCD_filter_h("grp_wrapped_HCD_filter_h_fu_52");
    grp_wrapped_HCD_filter_h_fu_52->ap_clk(ap_clk);
    grp_wrapped_HCD_filter_h_fu_52->ap_rst(ap_rst_n_inv);
    grp_wrapped_HCD_filter_h_fu_52->ap_start(grp_wrapped_HCD_filter_h_fu_52_ap_start);
    grp_wrapped_HCD_filter_h_fu_52->ap_done(grp_wrapped_HCD_filter_h_fu_52_ap_done);
    grp_wrapped_HCD_filter_h_fu_52->ap_idle(grp_wrapped_HCD_filter_h_fu_52_ap_idle);
    grp_wrapped_HCD_filter_h_fu_52->ap_ready(grp_wrapped_HCD_filter_h_fu_52_ap_ready);
    grp_wrapped_HCD_filter_h_fu_52->INPUT_STREAM_TDATA(INPUT_STREAM_TDATA_int);
    grp_wrapped_HCD_filter_h_fu_52->INPUT_STREAM_TVALID(INPUT_STREAM_TVALID_int);
    grp_wrapped_HCD_filter_h_fu_52->INPUT_STREAM_TREADY(grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TDATA(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TVALID(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TREADY(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TKEEP(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TSTRB(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TUSER(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TLAST(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TID(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID);
    grp_wrapped_HCD_filter_h_fu_52->OUTPUT_STREAM_TDEST(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST);
    regslice_both_INPUT_STREAM_data_V_U = new regslice_both<32>("regslice_both_INPUT_STREAM_data_V_U");
    regslice_both_INPUT_STREAM_data_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_data_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_data_V_U->data_in(INPUT_STREAM_TDATA);
    regslice_both_INPUT_STREAM_data_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_data_V_U->ack_in(regslice_both_INPUT_STREAM_data_V_U_ack_in);
    regslice_both_INPUT_STREAM_data_V_U->data_out(INPUT_STREAM_TDATA_int);
    regslice_both_INPUT_STREAM_data_V_U->vld_out(INPUT_STREAM_TVALID_int);
    regslice_both_INPUT_STREAM_data_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_data_V_U->apdone_blk(regslice_both_INPUT_STREAM_data_V_U_apdone_blk);
    regslice_both_INPUT_STREAM_keep_V_U = new regslice_both<4>("regslice_both_INPUT_STREAM_keep_V_U");
    regslice_both_INPUT_STREAM_keep_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_keep_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_keep_V_U->data_in(INPUT_STREAM_TKEEP);
    regslice_both_INPUT_STREAM_keep_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_keep_V_U->ack_in(regslice_both_INPUT_STREAM_keep_V_U_ack_in);
    regslice_both_INPUT_STREAM_keep_V_U->data_out(INPUT_STREAM_TKEEP_int);
    regslice_both_INPUT_STREAM_keep_V_U->vld_out(regslice_both_INPUT_STREAM_keep_V_U_vld_out);
    regslice_both_INPUT_STREAM_keep_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_keep_V_U->apdone_blk(regslice_both_INPUT_STREAM_keep_V_U_apdone_blk);
    regslice_both_INPUT_STREAM_strb_V_U = new regslice_both<4>("regslice_both_INPUT_STREAM_strb_V_U");
    regslice_both_INPUT_STREAM_strb_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_strb_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_strb_V_U->data_in(INPUT_STREAM_TSTRB);
    regslice_both_INPUT_STREAM_strb_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_strb_V_U->ack_in(regslice_both_INPUT_STREAM_strb_V_U_ack_in);
    regslice_both_INPUT_STREAM_strb_V_U->data_out(INPUT_STREAM_TSTRB_int);
    regslice_both_INPUT_STREAM_strb_V_U->vld_out(regslice_both_INPUT_STREAM_strb_V_U_vld_out);
    regslice_both_INPUT_STREAM_strb_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_strb_V_U->apdone_blk(regslice_both_INPUT_STREAM_strb_V_U_apdone_blk);
    regslice_both_INPUT_STREAM_user_V_U = new regslice_both<4>("regslice_both_INPUT_STREAM_user_V_U");
    regslice_both_INPUT_STREAM_user_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_user_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_user_V_U->data_in(INPUT_STREAM_TUSER);
    regslice_both_INPUT_STREAM_user_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_user_V_U->ack_in(regslice_both_INPUT_STREAM_user_V_U_ack_in);
    regslice_both_INPUT_STREAM_user_V_U->data_out(INPUT_STREAM_TUSER_int);
    regslice_both_INPUT_STREAM_user_V_U->vld_out(regslice_both_INPUT_STREAM_user_V_U_vld_out);
    regslice_both_INPUT_STREAM_user_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_user_V_U->apdone_blk(regslice_both_INPUT_STREAM_user_V_U_apdone_blk);
    regslice_both_INPUT_STREAM_last_V_U = new regslice_both<1>("regslice_both_INPUT_STREAM_last_V_U");
    regslice_both_INPUT_STREAM_last_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_last_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_last_V_U->data_in(INPUT_STREAM_TLAST);
    regslice_both_INPUT_STREAM_last_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_last_V_U->ack_in(regslice_both_INPUT_STREAM_last_V_U_ack_in);
    regslice_both_INPUT_STREAM_last_V_U->data_out(INPUT_STREAM_TLAST_int);
    regslice_both_INPUT_STREAM_last_V_U->vld_out(regslice_both_INPUT_STREAM_last_V_U_vld_out);
    regslice_both_INPUT_STREAM_last_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_last_V_U->apdone_blk(regslice_both_INPUT_STREAM_last_V_U_apdone_blk);
    regslice_both_INPUT_STREAM_id_V_U = new regslice_both<5>("regslice_both_INPUT_STREAM_id_V_U");
    regslice_both_INPUT_STREAM_id_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_id_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_id_V_U->data_in(INPUT_STREAM_TID);
    regslice_both_INPUT_STREAM_id_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_id_V_U->ack_in(regslice_both_INPUT_STREAM_id_V_U_ack_in);
    regslice_both_INPUT_STREAM_id_V_U->data_out(INPUT_STREAM_TID_int);
    regslice_both_INPUT_STREAM_id_V_U->vld_out(regslice_both_INPUT_STREAM_id_V_U_vld_out);
    regslice_both_INPUT_STREAM_id_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_id_V_U->apdone_blk(regslice_both_INPUT_STREAM_id_V_U_apdone_blk);
    regslice_both_INPUT_STREAM_dest_V_U = new regslice_both<5>("regslice_both_INPUT_STREAM_dest_V_U");
    regslice_both_INPUT_STREAM_dest_V_U->ap_clk(ap_clk);
    regslice_both_INPUT_STREAM_dest_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_INPUT_STREAM_dest_V_U->data_in(INPUT_STREAM_TDEST);
    regslice_both_INPUT_STREAM_dest_V_U->vld_in(INPUT_STREAM_TVALID);
    regslice_both_INPUT_STREAM_dest_V_U->ack_in(regslice_both_INPUT_STREAM_dest_V_U_ack_in);
    regslice_both_INPUT_STREAM_dest_V_U->data_out(INPUT_STREAM_TDEST_int);
    regslice_both_INPUT_STREAM_dest_V_U->vld_out(regslice_both_INPUT_STREAM_dest_V_U_vld_out);
    regslice_both_INPUT_STREAM_dest_V_U->ack_out(INPUT_STREAM_TREADY_int);
    regslice_both_INPUT_STREAM_dest_V_U->apdone_blk(regslice_both_INPUT_STREAM_dest_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_data_V_U = new regslice_both<32>("regslice_both_OUTPUT_STREAM_data_V_U");
    regslice_both_OUTPUT_STREAM_data_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_data_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_data_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA);
    regslice_both_OUTPUT_STREAM_data_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_data_V_U->ack_in(OUTPUT_STREAM_TREADY_int);
    regslice_both_OUTPUT_STREAM_data_V_U->data_out(OUTPUT_STREAM_TDATA);
    regslice_both_OUTPUT_STREAM_data_V_U->vld_out(regslice_both_OUTPUT_STREAM_data_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_data_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_data_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_keep_V_U = new regslice_both<4>("regslice_both_OUTPUT_STREAM_keep_V_U");
    regslice_both_OUTPUT_STREAM_keep_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_keep_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_keep_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP);
    regslice_both_OUTPUT_STREAM_keep_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_keep_V_U->ack_in(regslice_both_OUTPUT_STREAM_keep_V_U_ack_in_dummy);
    regslice_both_OUTPUT_STREAM_keep_V_U->data_out(OUTPUT_STREAM_TKEEP);
    regslice_both_OUTPUT_STREAM_keep_V_U->vld_out(regslice_both_OUTPUT_STREAM_keep_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_keep_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_keep_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_keep_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_strb_V_U = new regslice_both<4>("regslice_both_OUTPUT_STREAM_strb_V_U");
    regslice_both_OUTPUT_STREAM_strb_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_strb_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_strb_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB);
    regslice_both_OUTPUT_STREAM_strb_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_strb_V_U->ack_in(regslice_both_OUTPUT_STREAM_strb_V_U_ack_in_dummy);
    regslice_both_OUTPUT_STREAM_strb_V_U->data_out(OUTPUT_STREAM_TSTRB);
    regslice_both_OUTPUT_STREAM_strb_V_U->vld_out(regslice_both_OUTPUT_STREAM_strb_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_strb_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_strb_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_strb_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_user_V_U = new regslice_both<4>("regslice_both_OUTPUT_STREAM_user_V_U");
    regslice_both_OUTPUT_STREAM_user_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_user_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_user_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER);
    regslice_both_OUTPUT_STREAM_user_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_user_V_U->ack_in(regslice_both_OUTPUT_STREAM_user_V_U_ack_in_dummy);
    regslice_both_OUTPUT_STREAM_user_V_U->data_out(OUTPUT_STREAM_TUSER);
    regslice_both_OUTPUT_STREAM_user_V_U->vld_out(regslice_both_OUTPUT_STREAM_user_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_user_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_user_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_user_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_last_V_U = new regslice_both<1>("regslice_both_OUTPUT_STREAM_last_V_U");
    regslice_both_OUTPUT_STREAM_last_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_last_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_last_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST);
    regslice_both_OUTPUT_STREAM_last_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_last_V_U->ack_in(regslice_both_OUTPUT_STREAM_last_V_U_ack_in_dummy);
    regslice_both_OUTPUT_STREAM_last_V_U->data_out(OUTPUT_STREAM_TLAST);
    regslice_both_OUTPUT_STREAM_last_V_U->vld_out(regslice_both_OUTPUT_STREAM_last_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_last_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_last_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_last_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_id_V_U = new regslice_both<5>("regslice_both_OUTPUT_STREAM_id_V_U");
    regslice_both_OUTPUT_STREAM_id_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_id_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_id_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID);
    regslice_both_OUTPUT_STREAM_id_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_id_V_U->ack_in(regslice_both_OUTPUT_STREAM_id_V_U_ack_in_dummy);
    regslice_both_OUTPUT_STREAM_id_V_U->data_out(OUTPUT_STREAM_TID);
    regslice_both_OUTPUT_STREAM_id_V_U->vld_out(regslice_both_OUTPUT_STREAM_id_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_id_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_id_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_id_V_U_apdone_blk);
    regslice_both_OUTPUT_STREAM_dest_V_U = new regslice_both<5>("regslice_both_OUTPUT_STREAM_dest_V_U");
    regslice_both_OUTPUT_STREAM_dest_V_U->ap_clk(ap_clk);
    regslice_both_OUTPUT_STREAM_dest_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_OUTPUT_STREAM_dest_V_U->data_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST);
    regslice_both_OUTPUT_STREAM_dest_V_U->vld_in(grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID);
    regslice_both_OUTPUT_STREAM_dest_V_U->ack_in(regslice_both_OUTPUT_STREAM_dest_V_U_ack_in_dummy);
    regslice_both_OUTPUT_STREAM_dest_V_U->data_out(OUTPUT_STREAM_TDEST);
    regslice_both_OUTPUT_STREAM_dest_V_U->vld_out(regslice_both_OUTPUT_STREAM_dest_V_U_vld_out);
    regslice_both_OUTPUT_STREAM_dest_V_U->ack_out(OUTPUT_STREAM_TREADY);
    regslice_both_OUTPUT_STREAM_dest_V_U->apdone_blk(regslice_both_OUTPUT_STREAM_dest_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( INPUT_STREAM_TVALID );
    sensitive << ( regslice_both_INPUT_STREAM_data_V_U_ack_in );

    SC_METHOD(thread_INPUT_STREAM_TREADY_int);
    sensitive << ( grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( regslice_both_OUTPUT_STREAM_data_V_U_vld_out );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( OUTPUT_STREAM_TREADY_int );

    SC_METHOD(thread_grp_wrapped_HCD_filter_h_fu_52_ap_start);
    sensitive << ( grp_wrapped_HCD_filter_h_fu_52_ap_start_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_wrapped_HCD_filter_h_fu_52_ap_done );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0001";
    grp_wrapped_HCD_filter_h_fu_52_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "HLS_accel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_ap_start, "grp_wrapped_HCD_filter_h_fu_52_ap_start");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_ap_done, "grp_wrapped_HCD_filter_h_fu_52_ap_done");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_ap_idle, "grp_wrapped_HCD_filter_h_fu_52_ap_idle");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_ap_ready, "grp_wrapped_HCD_filter_h_fu_52_ap_ready");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY, "grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST, "grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, grp_wrapped_HCD_filter_h_fu_52_ap_start_reg, "grp_wrapped_HCD_filter_h_fu_52_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_data_V_U_apdone_blk, "regslice_both_INPUT_STREAM_data_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA_int, "INPUT_STREAM_TDATA_int");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID_int, "INPUT_STREAM_TVALID_int");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY_int, "INPUT_STREAM_TREADY_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_data_V_U_ack_in, "regslice_both_INPUT_STREAM_data_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_keep_V_U_apdone_blk, "regslice_both_INPUT_STREAM_keep_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP_int, "INPUT_STREAM_TKEEP_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_keep_V_U_vld_out, "regslice_both_INPUT_STREAM_keep_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_keep_V_U_ack_in, "regslice_both_INPUT_STREAM_keep_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_strb_V_U_apdone_blk, "regslice_both_INPUT_STREAM_strb_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB_int, "INPUT_STREAM_TSTRB_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_strb_V_U_vld_out, "regslice_both_INPUT_STREAM_strb_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_strb_V_U_ack_in, "regslice_both_INPUT_STREAM_strb_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_user_V_U_apdone_blk, "regslice_both_INPUT_STREAM_user_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER_int, "INPUT_STREAM_TUSER_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_user_V_U_vld_out, "regslice_both_INPUT_STREAM_user_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_user_V_U_ack_in, "regslice_both_INPUT_STREAM_user_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_last_V_U_apdone_blk, "regslice_both_INPUT_STREAM_last_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST_int, "INPUT_STREAM_TLAST_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_last_V_U_vld_out, "regslice_both_INPUT_STREAM_last_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_last_V_U_ack_in, "regslice_both_INPUT_STREAM_last_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_id_V_U_apdone_blk, "regslice_both_INPUT_STREAM_id_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TID_int, "INPUT_STREAM_TID_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_id_V_U_vld_out, "regslice_both_INPUT_STREAM_id_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_id_V_U_ack_in, "regslice_both_INPUT_STREAM_id_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_dest_V_U_apdone_blk, "regslice_both_INPUT_STREAM_dest_V_U_apdone_blk");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST_int, "INPUT_STREAM_TDEST_int");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_dest_V_U_vld_out, "regslice_both_INPUT_STREAM_dest_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_INPUT_STREAM_dest_V_U_ack_in, "regslice_both_INPUT_STREAM_dest_V_U_ack_in");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY_int, "OUTPUT_STREAM_TREADY_int");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_data_V_U_vld_out, "regslice_both_OUTPUT_STREAM_data_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_keep_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_keep_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_keep_V_U_ack_in_dummy, "regslice_both_OUTPUT_STREAM_keep_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_keep_V_U_vld_out, "regslice_both_OUTPUT_STREAM_keep_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_strb_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_strb_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_strb_V_U_ack_in_dummy, "regslice_both_OUTPUT_STREAM_strb_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_strb_V_U_vld_out, "regslice_both_OUTPUT_STREAM_strb_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_user_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_user_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_user_V_U_ack_in_dummy, "regslice_both_OUTPUT_STREAM_user_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_user_V_U_vld_out, "regslice_both_OUTPUT_STREAM_user_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_last_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_last_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_last_V_U_ack_in_dummy, "regslice_both_OUTPUT_STREAM_last_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_last_V_U_vld_out, "regslice_both_OUTPUT_STREAM_last_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_id_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_id_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_id_V_U_ack_in_dummy, "regslice_both_OUTPUT_STREAM_id_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_id_V_U_vld_out, "regslice_both_OUTPUT_STREAM_id_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_dest_V_U_apdone_blk, "regslice_both_OUTPUT_STREAM_dest_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_dest_V_U_ack_in_dummy, "regslice_both_OUTPUT_STREAM_dest_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_OUTPUT_STREAM_dest_V_U_vld_out, "regslice_both_OUTPUT_STREAM_dest_V_U_vld_out");
#endif

    }
    mHdltvinHandle.open("HLS_accel.hdltvin.dat");
    mHdltvoutHandle.open("HLS_accel.hdltvout.dat");
}

HLS_accel::~HLS_accel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete HLS_accel_CONTROL_BUS_s_axi_U;
    delete grp_wrapped_HCD_filter_h_fu_52;
    delete regslice_both_INPUT_STREAM_data_V_U;
    delete regslice_both_INPUT_STREAM_keep_V_U;
    delete regslice_both_INPUT_STREAM_strb_V_U;
    delete regslice_both_INPUT_STREAM_user_V_U;
    delete regslice_both_INPUT_STREAM_last_V_U;
    delete regslice_both_INPUT_STREAM_id_V_U;
    delete regslice_both_INPUT_STREAM_dest_V_U;
    delete regslice_both_OUTPUT_STREAM_data_V_U;
    delete regslice_both_OUTPUT_STREAM_keep_V_U;
    delete regslice_both_OUTPUT_STREAM_strb_V_U;
    delete regslice_both_OUTPUT_STREAM_user_V_U;
    delete regslice_both_OUTPUT_STREAM_last_V_U;
    delete regslice_both_OUTPUT_STREAM_id_V_U;
    delete regslice_both_OUTPUT_STREAM_dest_V_U;
}

void HLS_accel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void HLS_accel::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_wrapped_HCD_filter_h_fu_52_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            grp_wrapped_HCD_filter_h_fu_52_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_wrapped_HCD_filter_h_fu_52_ap_ready.read())) {
            grp_wrapped_HCD_filter_h_fu_52_ap_start_reg = ap_const_logic_0;
        }
    }
}

void HLS_accel::thread_INPUT_STREAM_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, INPUT_STREAM_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_INPUT_STREAM_data_V_U_ack_in.read()))) {
        INPUT_STREAM_TREADY = ap_const_logic_1;
    } else {
        INPUT_STREAM_TREADY = ap_const_logic_0;
    }
}

void HLS_accel::thread_INPUT_STREAM_TREADY_int() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        INPUT_STREAM_TREADY_int = grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY.read();
    } else {
        INPUT_STREAM_TREADY_int = ap_const_logic_0;
    }
}

void HLS_accel::thread_OUTPUT_STREAM_TVALID() {
    OUTPUT_STREAM_TVALID = regslice_both_OUTPUT_STREAM_data_V_U_vld_out.read();
}

void HLS_accel::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void HLS_accel::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void HLS_accel::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void HLS_accel::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void HLS_accel::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void HLS_accel::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void HLS_accel::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void HLS_accel::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void HLS_accel::thread_grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY() {
    grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY = (ap_CS_fsm_state3.read() & OUTPUT_STREAM_TREADY_int.read());
}

void HLS_accel::thread_grp_wrapped_HCD_filter_h_fu_52_ap_start() {
    grp_wrapped_HCD_filter_h_fu_52_ap_start = grp_wrapped_HCD_filter_h_fu_52_ap_start_reg.read();
}

void HLS_accel::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_wrapped_HCD_filter_h_fu_52_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

void HLS_accel::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDATA\" :  \"" << INPUT_STREAM_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TVALID\" :  \"" << INPUT_STREAM_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"INPUT_STREAM_TREADY\" :  \"" << INPUT_STREAM_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TKEEP\" :  \"" << INPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TSTRB\" :  \"" << INPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TUSER\" :  \"" << INPUT_STREAM_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TLAST\" :  \"" << INPUT_STREAM_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TID\" :  \"" << INPUT_STREAM_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDEST\" :  \"" << INPUT_STREAM_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDATA\" :  \"" << OUTPUT_STREAM_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TVALID\" :  \"" << OUTPUT_STREAM_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_STREAM_TREADY\" :  \"" << OUTPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TKEEP\" :  \"" << OUTPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TSTRB\" :  \"" << OUTPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TUSER\" :  \"" << OUTPUT_STREAM_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TLAST\" :  \"" << OUTPUT_STREAM_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TID\" :  \"" << OUTPUT_STREAM_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDEST\" :  \"" << OUTPUT_STREAM_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

