// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _HLS_accel_HH_
#define _HLS_accel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "wrapped_HCD_filter_h.h"
#include "HLS_accel_CONTROL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 4,
         unsigned int C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32>
struct HLS_accel : public sc_module {
    // Port declarations 38
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > INPUT_STREAM_TDATA;
    sc_in< sc_logic > INPUT_STREAM_TVALID;
    sc_out< sc_logic > INPUT_STREAM_TREADY;
    sc_in< sc_lv<4> > INPUT_STREAM_TKEEP;
    sc_in< sc_lv<4> > INPUT_STREAM_TSTRB;
    sc_in< sc_lv<4> > INPUT_STREAM_TUSER;
    sc_in< sc_lv<1> > INPUT_STREAM_TLAST;
    sc_in< sc_lv<5> > INPUT_STREAM_TID;
    sc_in< sc_lv<5> > INPUT_STREAM_TDEST;
    sc_out< sc_lv<32> > OUTPUT_STREAM_TDATA;
    sc_out< sc_logic > OUTPUT_STREAM_TVALID;
    sc_in< sc_logic > OUTPUT_STREAM_TREADY;
    sc_out< sc_lv<4> > OUTPUT_STREAM_TKEEP;
    sc_out< sc_lv<4> > OUTPUT_STREAM_TSTRB;
    sc_out< sc_lv<4> > OUTPUT_STREAM_TUSER;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TLAST;
    sc_out< sc_lv<5> > OUTPUT_STREAM_TID;
    sc_out< sc_lv<5> > OUTPUT_STREAM_TDEST;
    sc_in< sc_logic > s_axi_CONTROL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CONTROL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH/8> > s_axi_CONTROL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CONTROL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CONTROL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CONTROL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    HLS_accel(sc_module_name name);
    SC_HAS_PROCESS(HLS_accel);

    ~HLS_accel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    HLS_accel_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>* HLS_accel_CONTROL_BUS_s_axi_U;
    wrapped_HCD_filter_h* grp_wrapped_HCD_filter_h_fu_52;
    regslice_both<32>* regslice_both_INPUT_STREAM_data_V_U;
    regslice_both<4>* regslice_both_INPUT_STREAM_keep_V_U;
    regslice_both<4>* regslice_both_INPUT_STREAM_strb_V_U;
    regslice_both<4>* regslice_both_INPUT_STREAM_user_V_U;
    regslice_both<1>* regslice_both_INPUT_STREAM_last_V_U;
    regslice_both<5>* regslice_both_INPUT_STREAM_id_V_U;
    regslice_both<5>* regslice_both_INPUT_STREAM_dest_V_U;
    regslice_both<32>* regslice_both_OUTPUT_STREAM_data_V_U;
    regslice_both<4>* regslice_both_OUTPUT_STREAM_keep_V_U;
    regslice_both<4>* regslice_both_OUTPUT_STREAM_strb_V_U;
    regslice_both<4>* regslice_both_OUTPUT_STREAM_user_V_U;
    regslice_both<1>* regslice_both_OUTPUT_STREAM_last_V_U;
    regslice_both<5>* regslice_both_OUTPUT_STREAM_id_V_U;
    regslice_both<5>* regslice_both_OUTPUT_STREAM_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_ap_start;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_ap_done;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_ap_idle;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_ap_ready;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_INPUT_STREAM_TREADY;
    sc_signal< sc_lv<32> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDATA;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TVALID;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY;
    sc_signal< sc_lv<4> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TKEEP;
    sc_signal< sc_lv<4> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TSTRB;
    sc_signal< sc_lv<4> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TUSER;
    sc_signal< sc_lv<1> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TLAST;
    sc_signal< sc_lv<5> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TID;
    sc_signal< sc_lv<5> > grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TDEST;
    sc_signal< sc_logic > grp_wrapped_HCD_filter_h_fu_52_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_data_V_U_apdone_blk;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_data_V_U_apdone_blk;
    sc_signal< sc_lv<32> > INPUT_STREAM_TDATA_int;
    sc_signal< sc_logic > INPUT_STREAM_TVALID_int;
    sc_signal< sc_logic > INPUT_STREAM_TREADY_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_keep_V_U_apdone_blk;
    sc_signal< sc_lv<4> > INPUT_STREAM_TKEEP_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_strb_V_U_apdone_blk;
    sc_signal< sc_lv<4> > INPUT_STREAM_TSTRB_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_user_V_U_apdone_blk;
    sc_signal< sc_lv<4> > INPUT_STREAM_TUSER_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > INPUT_STREAM_TLAST_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_id_V_U_apdone_blk;
    sc_signal< sc_lv<5> > INPUT_STREAM_TID_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_dest_V_U_apdone_blk;
    sc_signal< sc_lv<5> > INPUT_STREAM_TDEST_int;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_INPUT_STREAM_dest_V_U_ack_in;
    sc_signal< sc_logic > OUTPUT_STREAM_TREADY_int;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_OUTPUT_STREAM_dest_V_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_INPUT_STREAM_TREADY();
    void thread_INPUT_STREAM_TREADY_int();
    void thread_OUTPUT_STREAM_TVALID();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_grp_wrapped_HCD_filter_h_fu_52_OUTPUT_STREAM_TREADY();
    void thread_grp_wrapped_HCD_filter_h_fu_52_ap_start();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
