// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "wrapped_HCD_filter_h.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic wrapped_HCD_filter_h::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic wrapped_HCD_filter_h::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state1 = "1";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state2 = "10";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state3 = "100";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state4 = "1000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state5 = "10000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state6 = "100000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> wrapped_HCD_filter_h::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_3 = "11";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_6 = "110";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_A = "1010";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_1 = "1";
const sc_lv<1> wrapped_HCD_filter_h::ap_const_lv1_0 = "0";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_2 = "10";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_4 = "100";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_5 = "101";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_8 = "1000";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_9 = "1001";
const sc_lv<9> wrapped_HCD_filter_h::ap_const_lv9_0 = "000000000";
const sc_lv<1> wrapped_HCD_filter_h::ap_const_lv1_1 = "1";
const sc_lv<32> wrapped_HCD_filter_h::ap_const_lv32_7 = "111";
const sc_lv<4> wrapped_HCD_filter_h::ap_const_lv4_F = "1111";
const sc_lv<4> wrapped_HCD_filter_h::ap_const_lv4_0 = "0000";
const sc_lv<5> wrapped_HCD_filter_h::ap_const_lv5_0 = "00000";
const sc_lv<9> wrapped_HCD_filter_h::ap_const_lv9_100 = "100000000";
const sc_lv<9> wrapped_HCD_filter_h::ap_const_lv9_1 = "1";
const sc_lv<8> wrapped_HCD_filter_h::ap_const_lv8_0 = "00000000";
const sc_lv<16> wrapped_HCD_filter_h::ap_const_lv16_FFFF = "1111111111111111";
const bool wrapped_HCD_filter_h::ap_const_boolean_1 = true;

wrapped_HCD_filter_h::wrapped_HCD_filter_h(sc_module_name name) : sc_module(name), mVcdFile(0) {
    I_x_U = new wrapped_HCD_filteibs("I_x_U");
    I_x_U->clk(ap_clk);
    I_x_U->reset(ap_rst);
    I_x_U->address0(I_x_address0);
    I_x_U->ce0(I_x_ce0);
    I_x_U->we0(I_x_we0);
    I_x_U->d0(grp_pop_stream_4_5_5_s_fu_229_ap_return);
    I_x_U->q0(I_x_q0);
    I_y_U = new wrapped_HCD_filteibs("I_y_U");
    I_y_U->clk(ap_clk);
    I_y_U->reset(ap_rst);
    I_y_U->address0(I_y_address0);
    I_y_U->ce0(I_y_ce0);
    I_y_U->we0(I_y_we0);
    I_y_U->d0(grp_pop_stream_4_5_5_s_fu_229_ap_return);
    I_y_U->q0(I_y_q0);
    output_img_U = new wrapped_HCD_filtekbM("output_img_U");
    output_img_U->clk(ap_clk);
    output_img_U->reset(ap_rst);
    output_img_U->address0(output_img_address0);
    output_img_U->ce0(output_img_ce0);
    output_img_U->we0(output_img_we0);
    output_img_U->d0(grp_HCD_filter_hw_fu_222_output_img_d0);
    output_img_U->q0(output_img_q0);
    grp_HCD_filter_hw_fu_222 = new HCD_filter_hw("grp_HCD_filter_hw_fu_222");
    grp_HCD_filter_hw_fu_222->ap_clk(ap_clk);
    grp_HCD_filter_hw_fu_222->ap_rst(ap_rst);
    grp_HCD_filter_hw_fu_222->ap_start(grp_HCD_filter_hw_fu_222_ap_start);
    grp_HCD_filter_hw_fu_222->ap_done(grp_HCD_filter_hw_fu_222_ap_done);
    grp_HCD_filter_hw_fu_222->ap_idle(grp_HCD_filter_hw_fu_222_ap_idle);
    grp_HCD_filter_hw_fu_222->ap_ready(grp_HCD_filter_hw_fu_222_ap_ready);
    grp_HCD_filter_hw_fu_222->I_x_address0(grp_HCD_filter_hw_fu_222_I_x_address0);
    grp_HCD_filter_hw_fu_222->I_x_ce0(grp_HCD_filter_hw_fu_222_I_x_ce0);
    grp_HCD_filter_hw_fu_222->I_x_q0(I_x_q0);
    grp_HCD_filter_hw_fu_222->I_y_address0(grp_HCD_filter_hw_fu_222_I_y_address0);
    grp_HCD_filter_hw_fu_222->I_y_ce0(grp_HCD_filter_hw_fu_222_I_y_ce0);
    grp_HCD_filter_hw_fu_222->I_y_q0(I_y_q0);
    grp_HCD_filter_hw_fu_222->output_img_address0(grp_HCD_filter_hw_fu_222_output_img_address0);
    grp_HCD_filter_hw_fu_222->output_img_ce0(grp_HCD_filter_hw_fu_222_output_img_ce0);
    grp_HCD_filter_hw_fu_222->output_img_we0(grp_HCD_filter_hw_fu_222_output_img_we0);
    grp_HCD_filter_hw_fu_222->output_img_d0(grp_HCD_filter_hw_fu_222_output_img_d0);
    grp_pop_stream_4_5_5_s_fu_229 = new pop_stream_4_5_5_s("grp_pop_stream_4_5_5_s_fu_229");
    grp_pop_stream_4_5_5_s_fu_229->ap_clk(ap_clk);
    grp_pop_stream_4_5_5_s_fu_229->ap_rst(ap_rst);
    grp_pop_stream_4_5_5_s_fu_229->ap_start(grp_pop_stream_4_5_5_s_fu_229_ap_start);
    grp_pop_stream_4_5_5_s_fu_229->ap_done(grp_pop_stream_4_5_5_s_fu_229_ap_done);
    grp_pop_stream_4_5_5_s_fu_229->ap_idle(grp_pop_stream_4_5_5_s_fu_229_ap_idle);
    grp_pop_stream_4_5_5_s_fu_229->ap_ready(grp_pop_stream_4_5_5_s_fu_229_ap_ready);
    grp_pop_stream_4_5_5_s_fu_229->INPUT_STREAM_TDATA(INPUT_STREAM_TDATA);
    grp_pop_stream_4_5_5_s_fu_229->INPUT_STREAM_TVALID(INPUT_STREAM_TVALID);
    grp_pop_stream_4_5_5_s_fu_229->INPUT_STREAM_TREADY(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TREADY);
    grp_pop_stream_4_5_5_s_fu_229->ap_return(grp_pop_stream_4_5_5_s_fu_229_ap_return);
    grp_pop_stream_4_5_5_s_fu_229->INPUT_STREAM_TDATA_blk_n(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_INPUT_STREAM_TDATA_blk_n);
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TREADY );

    SC_METHOD(thread_I_x_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_HCD_filter_hw_fu_222_I_x_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln126_1_fu_282_p1 );

    SC_METHOD(thread_I_x_ce0);
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_HCD_filter_hw_fu_222_I_x_ce0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_I_x_we0);
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_I_y_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_HCD_filter_hw_fu_222_I_y_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln136_1_fu_331_p1 );

    SC_METHOD(thread_I_y_ce0);
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_HCD_filter_hw_fu_222_I_y_ce0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_I_y_we0);
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( output_img_q0 );

    SC_METHOD(thread_OUTPUT_STREAM_TDATA_blk_n);
    sensitive << ( OUTPUT_STREAM_TREADY );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( e_last_V_reg_500 );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( OUTPUT_STREAM_TREADY );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_add_ln126_fu_277_p2);
    sensitive << ( zext_ln122_reg_425 );
    sensitive << ( zext_ln126_fu_273_p1 );

    SC_METHOD(thread_add_ln136_fu_326_p2);
    sensitive << ( zext_ln132_reg_451 );
    sensitive << ( zext_ln136_fu_322_p1 );

    SC_METHOD(thread_add_ln147_fu_396_p2);
    sensitive << ( zext_ln145_1_reg_482 );
    sensitive << ( zext_ln147_fu_392_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln144_fu_335_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln144_fu_335_p2 );

    SC_METHOD(thread_e_last_V_fu_406_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln145_fu_375_p2 );
    sensitive << ( idx_fu_387_p2 );

    SC_METHOD(thread_grp_HCD_filter_hw_fu_222_ap_start);
    sensitive << ( grp_HCD_filter_hw_fu_222_ap_start_reg );

    SC_METHOD(thread_grp_pop_stream_4_5_5_s_fu_229_ap_start);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln121_fu_237_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( y_0_reg_156 );

    SC_METHOD(thread_icmp_ln122_fu_261_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( x_0_reg_167 );

    SC_METHOD(thread_icmp_ln131_fu_286_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y1_0_reg_178 );

    SC_METHOD(thread_icmp_ln132_fu_310_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( x2_0_reg_189 );

    SC_METHOD(thread_icmp_ln144_fu_335_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( y5_0_reg_200 );

    SC_METHOD(thread_icmp_ln145_fu_375_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( x6_0_reg_211 );

    SC_METHOD(thread_idx_fu_387_p2);
    sensitive << ( shl_ln_reg_477 );
    sensitive << ( zext_ln145_fu_371_p1 );

    SC_METHOD(thread_output_img_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_HCD_filter_hw_fu_222_output_img_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln147_1_fu_401_p1 );

    SC_METHOD(thread_output_img_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_HCD_filter_hw_fu_222_output_img_ce0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_img_we0);
    sensitive << ( grp_HCD_filter_hw_fu_222_output_img_we0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_shl_ln_fu_351_p3);
    sensitive << ( trunc_ln146_fu_347_p1 );

    SC_METHOD(thread_tmp_2_fu_249_p3);
    sensitive << ( y_0_reg_156 );

    SC_METHOD(thread_tmp_4_fu_298_p3);
    sensitive << ( y1_0_reg_178 );

    SC_METHOD(thread_tmp_6_fu_359_p3);
    sensitive << ( y5_0_reg_200 );

    SC_METHOD(thread_trunc_ln146_fu_347_p1);
    sensitive << ( y5_0_reg_200 );

    SC_METHOD(thread_x_1_fu_316_p2);
    sensitive << ( x2_0_reg_189 );

    SC_METHOD(thread_x_2_fu_381_p2);
    sensitive << ( x6_0_reg_211 );

    SC_METHOD(thread_x_fu_267_p2);
    sensitive << ( x_0_reg_167 );

    SC_METHOD(thread_y_1_fu_292_p2);
    sensitive << ( y1_0_reg_178 );

    SC_METHOD(thread_y_2_fu_341_p2);
    sensitive << ( y5_0_reg_200 );

    SC_METHOD(thread_y_fu_243_p2);
    sensitive << ( y_0_reg_156 );

    SC_METHOD(thread_zext_ln122_fu_257_p1);
    sensitive << ( tmp_2_fu_249_p3 );

    SC_METHOD(thread_zext_ln126_1_fu_282_p1);
    sensitive << ( add_ln126_reg_438 );

    SC_METHOD(thread_zext_ln126_fu_273_p1);
    sensitive << ( x_0_reg_167 );

    SC_METHOD(thread_zext_ln132_fu_306_p1);
    sensitive << ( tmp_4_fu_298_p3 );

    SC_METHOD(thread_zext_ln136_1_fu_331_p1);
    sensitive << ( add_ln136_reg_464 );

    SC_METHOD(thread_zext_ln136_fu_322_p1);
    sensitive << ( x2_0_reg_189 );

    SC_METHOD(thread_zext_ln145_1_fu_367_p1);
    sensitive << ( tmp_6_fu_359_p3 );

    SC_METHOD(thread_zext_ln145_fu_371_p1);
    sensitive << ( x6_0_reg_211 );

    SC_METHOD(thread_zext_ln147_1_fu_401_p1);
    sensitive << ( add_ln147_fu_396_p2 );

    SC_METHOD(thread_zext_ln147_fu_392_p1);
    sensitive << ( x6_0_reg_211 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( OUTPUT_STREAM_TREADY );
    sensitive << ( grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln121_fu_237_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln122_fu_261_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln131_fu_286_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln132_fu_310_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln144_fu_335_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln145_fu_375_p2 );
    sensitive << ( grp_HCD_filter_hw_fu_222_ap_done );
    sensitive << ( ap_CS_fsm_state8 );

    ap_CS_fsm = "00000000001";
    grp_HCD_filter_hw_fu_222_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "wrapped_HCD_filter_h_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n, "grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA_blk_n, "INPUT_STREAM_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA_blk_n, "OUTPUT_STREAM_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, y_fu_243_p2, "y_fu_243_p2");
    sc_trace(mVcdFile, y_reg_420, "y_reg_420");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln122_fu_257_p1, "zext_ln122_fu_257_p1");
    sc_trace(mVcdFile, zext_ln122_reg_425, "zext_ln122_reg_425");
    sc_trace(mVcdFile, icmp_ln121_fu_237_p2, "icmp_ln121_fu_237_p2");
    sc_trace(mVcdFile, x_fu_267_p2, "x_fu_267_p2");
    sc_trace(mVcdFile, x_reg_433, "x_reg_433");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln126_fu_277_p2, "add_ln126_fu_277_p2");
    sc_trace(mVcdFile, add_ln126_reg_438, "add_ln126_reg_438");
    sc_trace(mVcdFile, icmp_ln122_fu_261_p2, "icmp_ln122_fu_261_p2");
    sc_trace(mVcdFile, y_1_fu_292_p2, "y_1_fu_292_p2");
    sc_trace(mVcdFile, y_1_reg_446, "y_1_reg_446");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, zext_ln132_fu_306_p1, "zext_ln132_fu_306_p1");
    sc_trace(mVcdFile, zext_ln132_reg_451, "zext_ln132_reg_451");
    sc_trace(mVcdFile, icmp_ln131_fu_286_p2, "icmp_ln131_fu_286_p2");
    sc_trace(mVcdFile, x_1_fu_316_p2, "x_1_fu_316_p2");
    sc_trace(mVcdFile, x_1_reg_459, "x_1_reg_459");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, add_ln136_fu_326_p2, "add_ln136_fu_326_p2");
    sc_trace(mVcdFile, add_ln136_reg_464, "add_ln136_reg_464");
    sc_trace(mVcdFile, icmp_ln132_fu_310_p2, "icmp_ln132_fu_310_p2");
    sc_trace(mVcdFile, y_2_fu_341_p2, "y_2_fu_341_p2");
    sc_trace(mVcdFile, y_2_reg_472, "y_2_reg_472");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, shl_ln_fu_351_p3, "shl_ln_fu_351_p3");
    sc_trace(mVcdFile, shl_ln_reg_477, "shl_ln_reg_477");
    sc_trace(mVcdFile, icmp_ln144_fu_335_p2, "icmp_ln144_fu_335_p2");
    sc_trace(mVcdFile, zext_ln145_1_fu_367_p1, "zext_ln145_1_fu_367_p1");
    sc_trace(mVcdFile, zext_ln145_1_reg_482, "zext_ln145_1_reg_482");
    sc_trace(mVcdFile, x_2_fu_381_p2, "x_2_fu_381_p2");
    sc_trace(mVcdFile, x_2_reg_490, "x_2_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, icmp_ln145_fu_375_p2, "icmp_ln145_fu_375_p2");
    sc_trace(mVcdFile, e_last_V_fu_406_p2, "e_last_V_fu_406_p2");
    sc_trace(mVcdFile, e_last_V_reg_500, "e_last_V_reg_500");
    sc_trace(mVcdFile, I_x_address0, "I_x_address0");
    sc_trace(mVcdFile, I_x_ce0, "I_x_ce0");
    sc_trace(mVcdFile, I_x_we0, "I_x_we0");
    sc_trace(mVcdFile, I_x_q0, "I_x_q0");
    sc_trace(mVcdFile, I_y_address0, "I_y_address0");
    sc_trace(mVcdFile, I_y_ce0, "I_y_ce0");
    sc_trace(mVcdFile, I_y_we0, "I_y_we0");
    sc_trace(mVcdFile, I_y_q0, "I_y_q0");
    sc_trace(mVcdFile, output_img_address0, "output_img_address0");
    sc_trace(mVcdFile, output_img_ce0, "output_img_ce0");
    sc_trace(mVcdFile, output_img_we0, "output_img_we0");
    sc_trace(mVcdFile, output_img_q0, "output_img_q0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_ap_start, "grp_HCD_filter_hw_fu_222_ap_start");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_ap_done, "grp_HCD_filter_hw_fu_222_ap_done");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_ap_idle, "grp_HCD_filter_hw_fu_222_ap_idle");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_ap_ready, "grp_HCD_filter_hw_fu_222_ap_ready");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_I_x_address0, "grp_HCD_filter_hw_fu_222_I_x_address0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_I_x_ce0, "grp_HCD_filter_hw_fu_222_I_x_ce0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_I_y_address0, "grp_HCD_filter_hw_fu_222_I_y_address0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_I_y_ce0, "grp_HCD_filter_hw_fu_222_I_y_ce0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_output_img_address0, "grp_HCD_filter_hw_fu_222_output_img_address0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_output_img_ce0, "grp_HCD_filter_hw_fu_222_output_img_ce0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_output_img_we0, "grp_HCD_filter_hw_fu_222_output_img_we0");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_output_img_d0, "grp_HCD_filter_hw_fu_222_output_img_d0");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_ap_start, "grp_pop_stream_4_5_5_s_fu_229_ap_start");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_ap_done, "grp_pop_stream_4_5_5_s_fu_229_ap_done");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_ap_idle, "grp_pop_stream_4_5_5_s_fu_229_ap_idle");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_ap_ready, "grp_pop_stream_4_5_5_s_fu_229_ap_ready");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TREADY, "grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, grp_pop_stream_4_5_5_s_fu_229_ap_return, "grp_pop_stream_4_5_5_s_fu_229_ap_return");
    sc_trace(mVcdFile, y_0_reg_156, "y_0_reg_156");
    sc_trace(mVcdFile, x_0_reg_167, "x_0_reg_167");
    sc_trace(mVcdFile, y1_0_reg_178, "y1_0_reg_178");
    sc_trace(mVcdFile, x2_0_reg_189, "x2_0_reg_189");
    sc_trace(mVcdFile, y5_0_reg_200, "y5_0_reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, x6_0_reg_211, "x6_0_reg_211");
    sc_trace(mVcdFile, grp_HCD_filter_hw_fu_222_ap_start_reg, "grp_HCD_filter_hw_fu_222_ap_start_reg");
    sc_trace(mVcdFile, zext_ln126_1_fu_282_p1, "zext_ln126_1_fu_282_p1");
    sc_trace(mVcdFile, zext_ln136_1_fu_331_p1, "zext_ln136_1_fu_331_p1");
    sc_trace(mVcdFile, zext_ln147_1_fu_401_p1, "zext_ln147_1_fu_401_p1");
    sc_trace(mVcdFile, tmp_2_fu_249_p3, "tmp_2_fu_249_p3");
    sc_trace(mVcdFile, zext_ln126_fu_273_p1, "zext_ln126_fu_273_p1");
    sc_trace(mVcdFile, tmp_4_fu_298_p3, "tmp_4_fu_298_p3");
    sc_trace(mVcdFile, zext_ln136_fu_322_p1, "zext_ln136_fu_322_p1");
    sc_trace(mVcdFile, trunc_ln146_fu_347_p1, "trunc_ln146_fu_347_p1");
    sc_trace(mVcdFile, tmp_6_fu_359_p3, "tmp_6_fu_359_p3");
    sc_trace(mVcdFile, zext_ln145_fu_371_p1, "zext_ln145_fu_371_p1");
    sc_trace(mVcdFile, zext_ln147_fu_392_p1, "zext_ln147_fu_392_p1");
    sc_trace(mVcdFile, add_ln147_fu_396_p2, "add_ln147_fu_396_p2");
    sc_trace(mVcdFile, idx_fu_387_p2, "idx_fu_387_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

wrapped_HCD_filter_h::~wrapped_HCD_filter_h() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete I_x_U;
    delete I_y_U;
    delete output_img_U;
    delete grp_HCD_filter_hw_fu_222;
    delete grp_pop_stream_4_5_5_s_fu_229;
}

void wrapped_HCD_filter_h::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_HCD_filter_hw_fu_222_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             esl_seteq<1,1,1>(icmp_ln131_fu_286_p2.read(), ap_const_lv1_1))) {
            grp_HCD_filter_hw_fu_222_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_HCD_filter_hw_fu_222_ap_ready.read())) {
            grp_HCD_filter_hw_fu_222_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
        x2_0_reg_189 = x_1_reg_459.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln131_fu_286_p2.read()))) {
        x2_0_reg_189 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(OUTPUT_STREAM_TREADY.read(), ap_const_logic_1))) {
        x6_0_reg_211 = x_2_reg_490.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln144_fu_335_p2.read()))) {
        x6_0_reg_211 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
        x_0_reg_167 = x_reg_433.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln121_fu_237_p2.read(), ap_const_lv1_0))) {
        x_0_reg_167 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln121_fu_237_p2.read(), ap_const_lv1_1))) {
        y1_0_reg_178 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln132_fu_310_p2.read(), ap_const_lv1_1))) {
        y1_0_reg_178 = y_1_reg_446.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_fu_375_p2.read(), ap_const_lv1_1))) {
        y5_0_reg_200 = y_2_reg_472.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(grp_HCD_filter_hw_fu_222_ap_done.read(), ap_const_logic_1))) {
        y5_0_reg_200 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_fu_261_p2.read(), ap_const_lv1_1))) {
        y_0_reg_156 = y_reg_420.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        y_0_reg_156 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln122_fu_261_p2.read()))) {
        add_ln126_reg_438 = add_ln126_fu_277_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln132_fu_310_p2.read()))) {
        add_ln136_reg_464 = add_ln136_fu_326_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln145_fu_375_p2.read()))) {
        e_last_V_reg_500 = e_last_V_fu_406_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln144_fu_335_p2.read()))) {
        shl_ln_reg_477 = shl_ln_fu_351_p3.read();
        zext_ln145_1_reg_482 = zext_ln145_1_fu_367_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        x_1_reg_459 = x_1_fu_316_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        x_2_reg_490 = x_2_fu_381_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_reg_433 = x_fu_267_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_1_reg_446 = y_1_fu_292_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        y_2_reg_472 = y_2_fu_341_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        y_reg_420 = y_fu_243_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln121_fu_237_p2.read(), ap_const_lv1_0))) {
        zext_ln122_reg_425 = zext_ln122_fu_257_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln131_fu_286_p2.read()))) {
        zext_ln132_reg_451 = zext_ln132_fu_306_p1.read();
    }
}

void wrapped_HCD_filter_h::thread_INPUT_STREAM_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        INPUT_STREAM_TDATA_blk_n = grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read();
    } else {
        INPUT_STREAM_TDATA_blk_n = ap_const_logic_1;
    }
}

void wrapped_HCD_filter_h::thread_INPUT_STREAM_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        INPUT_STREAM_TREADY = grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TREADY.read();
    } else {
        INPUT_STREAM_TREADY = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_I_x_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        I_x_address0 =  (sc_lv<16>) (zext_ln126_1_fu_282_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        I_x_address0 = grp_HCD_filter_hw_fu_222_I_x_address0.read();
    } else {
        I_x_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void wrapped_HCD_filter_h::thread_I_x_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
        I_x_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        I_x_ce0 = grp_HCD_filter_hw_fu_222_I_x_ce0.read();
    } else {
        I_x_ce0 = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_I_x_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
        I_x_we0 = ap_const_logic_1;
    } else {
        I_x_we0 = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_I_y_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        I_y_address0 =  (sc_lv<16>) (zext_ln136_1_fu_331_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        I_y_address0 = grp_HCD_filter_hw_fu_222_I_y_address0.read();
    } else {
        I_y_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void wrapped_HCD_filter_h::thread_I_y_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
        I_y_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        I_y_ce0 = grp_HCD_filter_hw_fu_222_I_y_ce0.read();
    } else {
        I_y_ce0 = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_I_y_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
        I_y_we0 = ap_const_logic_1;
    } else {
        I_y_we0 = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = esl_zext<32,1>(output_img_q0.read());
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TDATA_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        OUTPUT_STREAM_TDATA_blk_n = OUTPUT_STREAM_TREADY.read();
    } else {
        OUTPUT_STREAM_TDATA_blk_n = ap_const_logic_1;
    }
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = ap_const_lv5_0;
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = ap_const_lv5_0;
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = ap_const_lv4_F;
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = e_last_V_reg_500.read();
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = ap_const_lv4_F;
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = ap_const_lv4_0;
}

void wrapped_HCD_filter_h::thread_OUTPUT_STREAM_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(OUTPUT_STREAM_TREADY.read(), ap_const_logic_1))) {
        OUTPUT_STREAM_TVALID = ap_const_logic_1;
    } else {
        OUTPUT_STREAM_TVALID = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_add_ln126_fu_277_p2() {
    add_ln126_fu_277_p2 = (!zext_ln122_reg_425.read().is_01() || !zext_ln126_fu_273_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln122_reg_425.read()) + sc_biguint<18>(zext_ln126_fu_273_p1.read()));
}

void wrapped_HCD_filter_h::thread_add_ln136_fu_326_p2() {
    add_ln136_fu_326_p2 = (!zext_ln132_reg_451.read().is_01() || !zext_ln136_fu_322_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln132_reg_451.read()) + sc_biguint<18>(zext_ln136_fu_322_p1.read()));
}

void wrapped_HCD_filter_h::thread_add_ln147_fu_396_p2() {
    add_ln147_fu_396_p2 = (!zext_ln145_1_reg_482.read().is_01() || !zext_ln147_fu_392_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln145_1_reg_482.read()) + sc_biguint<18>(zext_ln147_fu_392_p1.read()));
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void wrapped_HCD_filter_h::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void wrapped_HCD_filter_h::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(icmp_ln144_fu_335_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln144_fu_335_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_e_last_V_fu_406_p2() {
    e_last_V_fu_406_p2 = (!idx_fu_387_p2.read().is_01() || !ap_const_lv16_FFFF.is_01())? sc_lv<1>(): sc_lv<1>(idx_fu_387_p2.read() == ap_const_lv16_FFFF);
}

void wrapped_HCD_filter_h::thread_grp_HCD_filter_hw_fu_222_ap_start() {
    grp_HCD_filter_hw_fu_222_ap_start = grp_HCD_filter_hw_fu_222_ap_start_reg.read();
}

void wrapped_HCD_filter_h::thread_grp_pop_stream_4_5_5_s_fu_229_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        grp_pop_stream_4_5_5_s_fu_229_ap_start = ap_const_logic_1;
    } else {
        grp_pop_stream_4_5_5_s_fu_229_ap_start = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_icmp_ln121_fu_237_p2() {
    icmp_ln121_fu_237_p2 = (!y_0_reg_156.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_156.read() == ap_const_lv9_100);
}

void wrapped_HCD_filter_h::thread_icmp_ln122_fu_261_p2() {
    icmp_ln122_fu_261_p2 = (!x_0_reg_167.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_167.read() == ap_const_lv9_100);
}

void wrapped_HCD_filter_h::thread_icmp_ln131_fu_286_p2() {
    icmp_ln131_fu_286_p2 = (!y1_0_reg_178.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(y1_0_reg_178.read() == ap_const_lv9_100);
}

void wrapped_HCD_filter_h::thread_icmp_ln132_fu_310_p2() {
    icmp_ln132_fu_310_p2 = (!x2_0_reg_189.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(x2_0_reg_189.read() == ap_const_lv9_100);
}

void wrapped_HCD_filter_h::thread_icmp_ln144_fu_335_p2() {
    icmp_ln144_fu_335_p2 = (!y5_0_reg_200.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(y5_0_reg_200.read() == ap_const_lv9_100);
}

void wrapped_HCD_filter_h::thread_icmp_ln145_fu_375_p2() {
    icmp_ln145_fu_375_p2 = (!x6_0_reg_211.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(x6_0_reg_211.read() == ap_const_lv9_100);
}

void wrapped_HCD_filter_h::thread_idx_fu_387_p2() {
    idx_fu_387_p2 = (!shl_ln_reg_477.read().is_01() || !zext_ln145_fu_371_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(shl_ln_reg_477.read()) + sc_biguint<16>(zext_ln145_fu_371_p1.read()));
}

void wrapped_HCD_filter_h::thread_output_img_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_img_address0 =  (sc_lv<16>) (zext_ln147_1_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_img_address0 = grp_HCD_filter_hw_fu_222_output_img_address0.read();
    } else {
        output_img_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void wrapped_HCD_filter_h::thread_output_img_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_img_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_img_ce0 = grp_HCD_filter_hw_fu_222_output_img_ce0.read();
    } else {
        output_img_ce0 = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_output_img_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_img_we0 = grp_HCD_filter_hw_fu_222_output_img_we0.read();
    } else {
        output_img_we0 = ap_const_logic_0;
    }
}

void wrapped_HCD_filter_h::thread_shl_ln_fu_351_p3() {
    shl_ln_fu_351_p3 = esl_concat<8,8>(trunc_ln146_fu_347_p1.read(), ap_const_lv8_0);
}

void wrapped_HCD_filter_h::thread_tmp_2_fu_249_p3() {
    tmp_2_fu_249_p3 = esl_concat<9,8>(y_0_reg_156.read(), ap_const_lv8_0);
}

void wrapped_HCD_filter_h::thread_tmp_4_fu_298_p3() {
    tmp_4_fu_298_p3 = esl_concat<9,8>(y1_0_reg_178.read(), ap_const_lv8_0);
}

void wrapped_HCD_filter_h::thread_tmp_6_fu_359_p3() {
    tmp_6_fu_359_p3 = esl_concat<9,8>(y5_0_reg_200.read(), ap_const_lv8_0);
}

void wrapped_HCD_filter_h::thread_trunc_ln146_fu_347_p1() {
    trunc_ln146_fu_347_p1 = y5_0_reg_200.read().range(8-1, 0);
}

void wrapped_HCD_filter_h::thread_x_1_fu_316_p2() {
    x_1_fu_316_p2 = (!x2_0_reg_189.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(x2_0_reg_189.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void wrapped_HCD_filter_h::thread_x_2_fu_381_p2() {
    x_2_fu_381_p2 = (!x6_0_reg_211.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(x6_0_reg_211.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void wrapped_HCD_filter_h::thread_x_fu_267_p2() {
    x_fu_267_p2 = (!x_0_reg_167.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(x_0_reg_167.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void wrapped_HCD_filter_h::thread_y_1_fu_292_p2() {
    y_1_fu_292_p2 = (!y1_0_reg_178.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(y1_0_reg_178.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void wrapped_HCD_filter_h::thread_y_2_fu_341_p2() {
    y_2_fu_341_p2 = (!y5_0_reg_200.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(y5_0_reg_200.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void wrapped_HCD_filter_h::thread_y_fu_243_p2() {
    y_fu_243_p2 = (!y_0_reg_156.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(y_0_reg_156.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void wrapped_HCD_filter_h::thread_zext_ln122_fu_257_p1() {
    zext_ln122_fu_257_p1 = esl_zext<18,17>(tmp_2_fu_249_p3.read());
}

void wrapped_HCD_filter_h::thread_zext_ln126_1_fu_282_p1() {
    zext_ln126_1_fu_282_p1 = esl_zext<64,18>(add_ln126_reg_438.read());
}

void wrapped_HCD_filter_h::thread_zext_ln126_fu_273_p1() {
    zext_ln126_fu_273_p1 = esl_zext<18,9>(x_0_reg_167.read());
}

void wrapped_HCD_filter_h::thread_zext_ln132_fu_306_p1() {
    zext_ln132_fu_306_p1 = esl_zext<18,17>(tmp_4_fu_298_p3.read());
}

void wrapped_HCD_filter_h::thread_zext_ln136_1_fu_331_p1() {
    zext_ln136_1_fu_331_p1 = esl_zext<64,18>(add_ln136_reg_464.read());
}

void wrapped_HCD_filter_h::thread_zext_ln136_fu_322_p1() {
    zext_ln136_fu_322_p1 = esl_zext<18,9>(x2_0_reg_189.read());
}

void wrapped_HCD_filter_h::thread_zext_ln145_1_fu_367_p1() {
    zext_ln145_1_fu_367_p1 = esl_zext<18,17>(tmp_6_fu_359_p3.read());
}

void wrapped_HCD_filter_h::thread_zext_ln145_fu_371_p1() {
    zext_ln145_fu_371_p1 = esl_zext<16,9>(x6_0_reg_211.read());
}

void wrapped_HCD_filter_h::thread_zext_ln147_1_fu_401_p1() {
    zext_ln147_1_fu_401_p1 = esl_zext<64,18>(add_ln147_fu_396_p2.read());
}

void wrapped_HCD_filter_h::thread_zext_ln147_fu_392_p1() {
    zext_ln147_fu_392_p1 = esl_zext<18,9>(x6_0_reg_211.read());
}

void wrapped_HCD_filter_h::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln121_fu_237_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln122_fu_261_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln131_fu_286_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln132_fu_310_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(grp_pop_stream_4_5_5_s_fu_229_INPUT_STREAM_TDATA_blk_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_HCD_filter_hw_fu_222_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln144_fu_335_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln145_fu_375_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(OUTPUT_STREAM_TREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

